package defpackage;
/* compiled from: r8-map-id-f559a6c9210f67746bd9ce87931ee85b676f3bda66e04dc5e85cb7e8eec71de1 */
/* renamed from: a2b  reason: default package */
/* loaded from: classes3.dex */
public final /* synthetic */ class a2b implements vt4 {
    public final /* synthetic */ int a;

    private final Object a() {
        return new pq9("string:browser_history", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 10987L, 51L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 9287L, 55L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 9747L, 43L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 13731L, 75L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 9130L, 47L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 9547L, 55L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 9903L, 55L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 14843L, 91L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 8907L, 51L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 9471L, 55L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 9879L, 39L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 9443L, 43L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 9491L, 47L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 9371L, 55L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 9467L, 59L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 12731L, 67L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 14495L, 87L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 9063L, 47L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 12695L, 67L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 8083L, 39L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 8007L, 39L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 10431L, 55L)}));
    }

    @Override // defpackage.vt4
    public final Object invoke() {
        switch (this.a) {
            case 0:
                return new pq9("string:word_origin", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 59410L, 55L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 48710L, 39L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 51018L, 35L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 73594L, 47L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 64959L, 39L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 50310L, 43L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 51986L, 39L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 77902L, 51L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 46662L, 31L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 49218L, 43L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 51762L, 35L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 49870L, 39L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 48874L, 47L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 49206L, 43L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 49878L, 43L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 67674L, 55L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 77466L, 55L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 48086L, 39L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 67550L, 63L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 41726L, 27L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 41462L, 27L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 79627L, 35L)}));
            case 1:
                return new pq9("string:word_replace", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 59466L, 56L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 48750L, 44L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 51054L, 36L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 73642L, 72L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 64999L, 44L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 50354L, 48L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 52026L, 48L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 77954L, 88L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 46694L, 40L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 49262L, 44L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 51798L, 32L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 49910L, 40L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 48922L, 44L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 49250L, 40L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 49922L, 56L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 67730L, 60L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 77522L, 52L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 48126L, 52L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 67614L, 60L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 41754L, 32L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 41490L, 32L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 79663L, 40L)}));
            case 2:
                return new pq9("string:year", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 59523L, 20L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 48795L, 16L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 51091L, 20L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 73715L, 24L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 65044L, 20L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 50403L, 20L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 52075L, 16L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 78043L, 28L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 46735L, 20L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 49307L, 20L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 51831L, 16L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 49951L, 16L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 48967L, 20L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 49291L, 16L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 49979L, 16L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 67791L, 20L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 77575L, 20L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 48179L, 20L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 67675L, 20L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 41787L, 16L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 41523L, 16L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 79704L, 20L)}));
            case 3:
                return new pq9("string:yesterday", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 59544L, 25L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 48812L, 25L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 51112L, 29L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 73740L, 29L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 65065L, 29L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 50424L, 25L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 52092L, 25L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 78072L, 25L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 46756L, 29L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 49328L, 25L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 51848L, 25L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 49968L, 25L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 48988L, 29L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 49308L, 29L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 49996L, 25L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 67812L, 33L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 77596L, 49L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 48200L, 25L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 67696L, 33L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 41804L, 25L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 41540L, 25L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 79725L, 29L)}));
            case 4:
                return new pq9("string:video_setting_seek_backward", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 63915L, 55L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 78347L, 47L)}));
            case 5:
                return new pq9("string:video_setting_pip", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 63556L, 49L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 77920L, 57L)}));
            case 6:
                return new pq9("string:video_setting_playback", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 63663L, 42L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 78039L, 46L)}));
            case 7:
                return new pq9("string:video_setting_playback_speed", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 63606L, 56L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 77978L, 60L)}));
            case 8:
                return new pq9("string:video_setting_resize_fill", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 63706L, 41L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 78086L, 49L)}));
            case 9:
                return new pq9("string:video_setting_resize_fit", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 63748L, 36L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 78136L, 56L)}));
            case 10:
                return new pq9("string:video_setting_resize_mode", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 63785L, 49L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 78193L, 61L)}));
            case 11:
                return new pq9("string:video_setting_resize_zoom", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 63835L, 41L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 78255L, 45L)}));
            case 12:
                return new pq9("string:video_setting_seek_forward", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 63971L, 50L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 78395L, 46L)}));
            case 13:
                return new pq9("string:video_setting_show_subtitle", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 64022L, 55L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 78442L, 67L)}));
            case 14:
                return new pq9("string:video_setting_speed_value", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 64078L, 41L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 78510L, 41L)}));
            case 15:
                return new pq9("string:video_setting_subtitle", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 64759L, 42L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 79223L, 46L)}));
            case 16:
                return new pq9("string:video_setting_subtitle_background_color", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 58838L, 75L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 48198L, 67L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 50510L, 71L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 72938L, 79L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 64120L, 71L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 49790L, 67L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 51490L, 67L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 77198L, 99L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 46166L, 63L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 48706L, 67L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 51266L, 59L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 49350L, 63L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 48378L, 71L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 48690L, 63L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 49370L, 63L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 67070L, 71L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 76782L, 87L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 47578L, 67L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 66930L, 71L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 41250L, 63L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 40986L, 63L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 78552L, 63L)}));
            case 17:
                return new pq9("string:video_setting_subtitle_background_opacity", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 64192L, 85L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 78616L, 89L)}));
            case 18:
                return new pq9("string:video_setting_subtitle_font_bold", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 58914L, 52L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 48266L, 52L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 50582L, 48L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 73018L, 56L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 64278L, 48L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 49858L, 52L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 51558L, 48L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 77298L, 56L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 46230L, 48L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 48774L, 52L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 51326L, 48L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 49414L, 48L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 48450L, 44L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 48754L, 56L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 49434L, 52L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 67142L, 56L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 76870L, 52L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 47646L, 48L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 67002L, 56L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 41314L, 48L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 41050L, 48L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 78706L, 48L)}));
            case 19:
                return new pq9("string:browser_fast_link", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 10937L, 49L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 9237L, 49L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 9701L, 45L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 13661L, 69L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 9088L, 41L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 9501L, 45L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 9857L, 45L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 14769L, 73L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 8865L, 41L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 9425L, 45L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 9821L, 57L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 9397L, 45L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 9445L, 45L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 9325L, 45L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 9421L, 45L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 12669L, 61L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 14425L, 69L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 9017L, 45L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 12633L, 61L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 8041L, 41L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 7965L, 41L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 10381L, 49L)}));
            case 20:
                return new pq9("string:cascade_block_heading5_desc", fca.B(new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11334L, 63L)));
            case 21:
                return a();
            case 22:
                return new pq9("string:cascade_block_heading6", fca.B(new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11513L, 50L)));
            case 23:
                return new pq9("string:cascade_block_heading6_desc", fca.B(new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11449L, 63L)));
            case 24:
                return new pq9("string:cascade_block_image", fca.B(new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11621L, 43L)));
            case 25:
                return new pq9("string:cascade_block_image_desc", fca.B(new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11564L, 56L)));
            case 26:
                return new pq9("string:cascade_block_numbered", fca.B(new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11745L, 50L)));
            case 27:
                return new pq9("string:cascade_block_numbered_desc", fca.B(new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11665L, 79L)));
            case 28:
                return new pq9("string:cascade_block_paragraph", fca.B(new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11873L, 47L)));
            default:
                return new pq9("string:cascade_block_paragraph_desc", fca.B(new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11796L, 76L)));
        }
    }
}
