package defpackage;

import java.security.GeneralSecurityException;
import java.util.Collections;
import java.util.HashMap;
/* compiled from: r8-map-id-f559a6c9210f67746bd9ce87931ee85b676f3bda66e04dc5e85cb7e8eec71de1 */
/* renamed from: dze  reason: default package */
/* loaded from: classes.dex */
public abstract class dze {
    static {
        int i = cif.a;
        try {
            a();
        } catch (GeneralSecurityException e) {
            throw new ExceptionInInitializerError(e);
        }
    }

    public static void a() {
        m5f m5fVar = m5f.b;
        m5fVar.a(hhe.f);
        m5fVar.b(hhe.g);
        m5fVar.a(hhe.h);
        m5fVar.b(hhe.i);
        wge.a();
        swe.a();
        if (lve.a()) {
            return;
        }
        i6f i6fVar = pxe.a;
        if (eub.d(1)) {
            y5f y5fVar = n0f.a;
            l5f l5fVar = l5f.b;
            l5fVar.h(n0f.a);
            l5fVar.g(n0f.b);
            l5fVar.f(n0f.c);
            l5fVar.e(n0f.d);
            l5fVar.f(n0f.e);
            l5fVar.e(n0f.f);
            g5f g5fVar = g5f.b;
            HashMap hashMap = new HashMap();
            yv b = yxe.b();
            uxe uxeVar = uxe.b;
            b.a = uxeVar;
            txe txeVar = txe.d;
            b.b = txeVar;
            wxe wxeVar = wxe.c;
            b.c = wxeVar;
            vxe vxeVar = vxe.b;
            b.e = vxeVar;
            odd b2 = gje.b();
            b2.l();
            b2.t(16);
            b2.x();
            fje fjeVar = fje.e;
            b2.e = fjeVar;
            b.M(b2.h());
            hashMap.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM", b.K());
            yv b3 = yxe.b();
            b3.a = uxeVar;
            b3.b = txeVar;
            b3.c = wxeVar;
            vxe vxeVar2 = vxe.d;
            b3.e = vxeVar2;
            odd b4 = gje.b();
            b4.l();
            b4.t(16);
            b4.x();
            b4.e = fjeVar;
            b3.M(b4.h());
            hashMap.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM_RAW", b3.K());
            yv b5 = yxe.b();
            b5.a = uxeVar;
            b5.b = txeVar;
            wxe wxeVar2 = wxe.b;
            b5.c = wxeVar2;
            b5.e = vxeVar;
            odd b6 = gje.b();
            b6.l();
            b6.t(16);
            b6.x();
            b6.e = fjeVar;
            b5.M(b6.h());
            hashMap.put("ECIES_P256_COMPRESSED_HKDF_HMAC_SHA256_AES128_GCM", b5.K());
            yv b7 = yxe.b();
            b7.a = uxeVar;
            b7.b = txeVar;
            b7.c = wxeVar2;
            b7.e = vxeVar2;
            odd b8 = gje.b();
            b8.l();
            b8.t(16);
            b8.x();
            b8.e = fjeVar;
            b7.M(b8.h());
            hashMap.put("ECIES_P256_COMPRESSED_HKDF_HMAC_SHA256_AES128_GCM_RAW", b7.K());
            yv b9 = yxe.b();
            b9.a = uxeVar;
            b9.b = txeVar;
            b9.c = wxeVar2;
            b9.e = vxeVar2;
            odd b10 = gje.b();
            b10.l();
            b10.t(16);
            b10.x();
            b10.e = fjeVar;
            b9.M(b10.h());
            hashMap.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM_COMPRESSED_WITHOUT_PREFIX", b9.K());
            yv b11 = yxe.b();
            b11.a = uxeVar;
            b11.b = txeVar;
            b11.c = wxeVar;
            b11.e = vxeVar;
            yv b12 = bie.b();
            b12.L(16);
            b12.N(32);
            b12.T(16);
            b12.Q(16);
            zhe zheVar = zhe.e;
            b12.e = zheVar;
            yhe yheVar = yhe.e;
            b12.f = yheVar;
            b11.M(b12.J());
            hashMap.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_CTR_HMAC_SHA256", b11.K());
            yv b13 = yxe.b();
            b13.a = uxeVar;
            b13.b = txeVar;
            b13.c = wxeVar;
            b13.e = vxeVar2;
            yv b14 = bie.b();
            b14.L(16);
            b14.N(32);
            b14.T(16);
            b14.Q(16);
            b14.e = zheVar;
            b14.f = yheVar;
            b13.M(b14.J());
            hashMap.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_CTR_HMAC_SHA256_RAW", b13.K());
            yv b15 = yxe.b();
            b15.a = uxeVar;
            b15.b = txeVar;
            b15.c = wxeVar2;
            b15.e = vxeVar;
            yv b16 = bie.b();
            b16.L(16);
            b16.N(32);
            b16.T(16);
            b16.Q(16);
            b16.e = zheVar;
            b16.f = yheVar;
            b15.M(b16.J());
            hashMap.put("ECIES_P256_COMPRESSED_HKDF_HMAC_SHA256_AES128_CTR_HMAC_SHA256", b15.K());
            yv b17 = yxe.b();
            b17.a = uxeVar;
            b17.b = txeVar;
            b17.c = wxeVar2;
            b17.e = vxeVar2;
            yv b18 = bie.b();
            b18.L(16);
            b18.N(32);
            b18.T(16);
            b18.Q(16);
            b18.e = zheVar;
            b18.f = yheVar;
            b17.M(b18.J());
            hashMap.put("ECIES_P256_COMPRESSED_HKDF_HMAC_SHA256_AES128_CTR_HMAC_SHA256_RAW", b17.K());
            g5fVar.b(Collections.unmodifiableMap(hashMap));
            m5fVar.b(pxe.a);
            m5fVar.b(pxe.b);
            y4f y4fVar = y4f.b;
            y4fVar.b(pxe.e, yxe.class);
            h3f h3fVar = h3f.d;
            h3fVar.c(pxe.c, true);
            h3fVar.c(pxe.d, false);
            i6f i6fVar2 = p1f.a;
            if (eub.d(1)) {
                l5fVar.h(rye.a);
                l5fVar.g(rye.b);
                l5fVar.f(rye.c);
                l5fVar.e(rye.d);
                l5fVar.f(rye.e);
                l5fVar.e(rye.f);
                HashMap hashMap2 = new HashMap();
                odd b19 = kye.b();
                gye gyeVar = gye.b;
                b19.e = gyeVar;
                hye hyeVar = hye.C;
                b19.b = hyeVar;
                fye fyeVar = fye.d;
                b19.c = fyeVar;
                eye eyeVar = eye.d;
                b19.d = eyeVar;
                hashMap2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_128_GCM", b19.i());
                odd b20 = kye.b();
                gye gyeVar2 = gye.d;
                b20.e = gyeVar2;
                b20.b = hyeVar;
                b20.c = fyeVar;
                b20.d = eyeVar;
                hashMap2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_128_GCM_RAW", b20.i());
                odd b21 = kye.b();
                b21.e = gyeVar;
                b21.b = hyeVar;
                b21.c = fyeVar;
                eye eyeVar2 = eye.e;
                b21.d = eyeVar2;
                hashMap2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_256_GCM", b21.i());
                odd b22 = kye.b();
                b22.e = gyeVar2;
                b22.b = hyeVar;
                b22.c = fyeVar;
                b22.d = eyeVar2;
                hashMap2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_256_GCM_RAW", b22.i());
                odd b23 = kye.b();
                b23.e = gyeVar;
                b23.b = hyeVar;
                b23.c = fyeVar;
                eye eyeVar3 = eye.f;
                b23.d = eyeVar3;
                hashMap2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_CHACHA20_POLY1305", b23.i());
                odd b24 = kye.b();
                b24.e = gyeVar2;
                b24.b = hyeVar;
                b24.c = fyeVar;
                b24.d = eyeVar3;
                hashMap2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_CHACHA20_POLY1305_RAW", b24.i());
                odd b25 = kye.b();
                b25.e = gyeVar;
                hye hyeVar2 = hye.d;
                b25.b = hyeVar2;
                b25.c = fyeVar;
                b25.d = eyeVar;
                hashMap2.put("DHKEM_P256_HKDF_SHA256_HKDF_SHA256_AES_128_GCM", b25.i());
                odd b26 = kye.b();
                b26.e = gyeVar2;
                b26.b = hyeVar2;
                b26.c = fyeVar;
                b26.d = eyeVar;
                hashMap2.put("DHKEM_P256_HKDF_SHA256_HKDF_SHA256_AES_128_GCM_RAW", b26.i());
                odd b27 = kye.b();
                b27.e = gyeVar;
                b27.b = hyeVar2;
                b27.c = fyeVar;
                b27.d = eyeVar2;
                hashMap2.put("DHKEM_P256_HKDF_SHA256_HKDF_SHA256_AES_256_GCM", b27.i());
                odd b28 = kye.b();
                b28.e = gyeVar2;
                b28.b = hyeVar2;
                b28.c = fyeVar;
                b28.d = eyeVar2;
                hashMap2.put("DHKEM_P256_HKDF_SHA256_HKDF_SHA256_AES_256_GCM_RAW", b28.i());
                odd b29 = kye.b();
                b29.e = gyeVar;
                hye hyeVar3 = hye.e;
                b29.b = hyeVar3;
                fye fyeVar2 = fye.e;
                b29.c = fyeVar2;
                b29.d = eyeVar;
                hashMap2.put("DHKEM_P384_HKDF_SHA384_HKDF_SHA384_AES_128_GCM", b29.i());
                odd b30 = kye.b();
                b30.e = gyeVar2;
                b30.b = hyeVar3;
                b30.c = fyeVar2;
                b30.d = eyeVar;
                hashMap2.put("DHKEM_P384_HKDF_SHA384_HKDF_SHA384_AES_128_GCM_RAW", b30.i());
                odd b31 = kye.b();
                b31.e = gyeVar;
                b31.b = hyeVar3;
                b31.c = fyeVar2;
                b31.d = eyeVar2;
                hashMap2.put("DHKEM_P384_HKDF_SHA384_HKDF_SHA384_AES_256_GCM", b31.i());
                odd b32 = kye.b();
                b32.e = gyeVar2;
                b32.b = hyeVar3;
                b32.c = fyeVar2;
                b32.d = eyeVar2;
                hashMap2.put("DHKEM_P384_HKDF_SHA384_HKDF_SHA384_AES_256_GCM_RAW", b32.i());
                odd b33 = kye.b();
                b33.e = gyeVar;
                hye hyeVar4 = hye.f;
                b33.b = hyeVar4;
                fye fyeVar3 = fye.f;
                b33.c = fyeVar3;
                b33.d = eyeVar;
                hashMap2.put("DHKEM_P521_HKDF_SHA512_HKDF_SHA512_AES_128_GCM", b33.i());
                odd b34 = kye.b();
                b34.e = gyeVar2;
                b34.b = hyeVar4;
                b34.c = fyeVar3;
                b34.d = eyeVar;
                hashMap2.put("DHKEM_P521_HKDF_SHA512_HKDF_SHA512_AES_128_GCM_RAW", b34.i());
                odd b35 = kye.b();
                b35.e = gyeVar;
                b35.b = hyeVar4;
                b35.c = fyeVar3;
                b35.d = eyeVar2;
                hashMap2.put("DHKEM_P521_HKDF_SHA512_HKDF_SHA512_AES_256_GCM", b35.i());
                odd b36 = kye.b();
                b36.e = gyeVar2;
                b36.b = hyeVar4;
                b36.c = fyeVar3;
                b36.d = eyeVar2;
                hashMap2.put("DHKEM_P521_HKDF_SHA512_HKDF_SHA512_AES_256_GCM_RAW", b36.i());
                g5fVar.b(Collections.unmodifiableMap(hashMap2));
                m5fVar.b(p1f.a);
                m5fVar.b(p1f.b);
                y4fVar.b(p1f.e, kye.class);
                h3fVar.c(p1f.c, true);
                h3fVar.c(p1f.d, false);
                return;
            }
            hfd.j("Registering HPKE Hybrid Encryption is not supported in FIPS mode");
            return;
        }
        hfd.j("Registering ECIES Hybrid Encryption is not supported in FIPS mode");
    }
}
