package defpackage;
/* compiled from: r8-map-id-f559a6c9210f67746bd9ce87931ee85b676f3bda66e04dc5e85cb7e8eec71de1 */
/* renamed from: e3b  reason: default package */
/* loaded from: classes3.dex */
public final /* synthetic */ class e3b implements vt4 {
    public final /* synthetic */ int a;

    private final Object A() {
        return new pq9("string:setting_reader_turn_page_volume_desc", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 41602L, 156L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 34426L, 100L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 36070L, 96L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 52082L, 160L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 46409L, 104L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 35382L, 112L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 36762L, 120L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 55262L, 176L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 33086L, 104L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 34746L, 100L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 36766L, 104L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 35398L, 100L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 34578L, 100L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 34650L, 116L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 35126L, 112L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 47938L, 156L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 54854L, 188L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 33794L, 112L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 47966L, 140L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 29562L, 72L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 29362L, 72L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57865L, 124L)}));
    }

    private final Object B() {
        return new pq9("string:setting_display_density_scale", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 33908L, 65L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 28100L, 61L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 29700L, 73L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 42520L, 81L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39734L, 57L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 28772L, 65L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 29884L, 69L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 45600L, 85L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 27036L, 61L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 28440L, 69L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 30524L, 53L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 29216L, 69L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 28512L, 61L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 28204L, 61L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 28508L, 65L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 38988L, 81L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 45036L, 97L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 27560L, 57L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 39040L, 81L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 24300L, 53L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 24092L, 53L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 49974L, 73L)}));
    }

    private final Object a() {
        return new pq9("string:setting_display_font_family", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 34465L, 47L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 28549L, 43L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 30193L, 51L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 43245L, 71L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 40155L, 43L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 29245L, 43L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 30401L, 43L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 46277L, 55L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 27481L, 43L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 28897L, 43L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 30965L, 51L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 29693L, 43L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 28969L, 51L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 28653L, 47L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 28977L, 43L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 39589L, 51L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 45681L, 55L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 28009L, 51L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 39685L, 51L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 24717L, 43L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 24513L, 43L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 50539L, 51L)}));
    }

    private final Object b() {
        return new pq9("string:setting_reader_translate_auto_desc", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 40087L, 170L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 33227L, 122L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 34891L, 122L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 50383L, 194L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 45083L, 130L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 34163L, 126L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 35551L, 126L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 53435L, 206L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 31911L, 138L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 33599L, 126L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 35575L, 114L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 34219L, 130L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 33455L, 114L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 33467L, 126L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 33859L, 150L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 46255L, 178L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 53035L, 194L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 32663L, 110L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 46303L, 186L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 28627L, 98L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 28427L, 98L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 56375L, 138L)}));
    }

    private final Object e() {
        return new pq9("string:setting_reader_translate_auto_label", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 40258L, 75L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 33350L, 67L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 35014L, 71L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 50578L, 95L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 45214L, 67L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 34290L, 79L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 35678L, 71L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 53642L, 91L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 32050L, 63L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 33726L, 75L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 35690L, 63L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 34350L, 63L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 33570L, 59L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 33594L, 75L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 34010L, 75L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 46434L, 95L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 53230L, 95L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 32774L, 63L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 46490L, 95L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 28726L, 59L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 28526L, 59L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 56514L, 67L)}));
    }

    private final Object f() {
        return new pq9("string:setting_reader_translate_detect_language", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 40424L, 80L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 33484L, 76L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 35160L, 72L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 50784L, 92L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 45352L, 72L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 34456L, 68L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 35820L, 80L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 53820L, 88L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 32188L, 68L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 33868L, 72L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 35808L, 64L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 34472L, 68L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 33704L, 64L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 33744L, 72L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 34172L, 76L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 46612L, 92L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 53432L, 92L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 32900L, 68L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 46680L, 88L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 28840L, 64L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 28640L, 64L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 56660L, 84L)}));
    }

    private final Object g() {
        return new pq9("string:setting_reader_translate_qt", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 40674L, 55L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 33686L, 55L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 35362L, 55L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 51050L, 55L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 45550L, 55L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 34650L, 55L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 36034L, 55L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 54090L, 55L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 32378L, 55L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 34062L, 55L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 35978L, 55L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 34674L, 55L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 33882L, 55L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 33954L, 55L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 34398L, 55L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 46886L, 55L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 53686L, 55L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 33090L, 55L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 46950L, 55L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 29010L, 55L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 28810L, 55L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 56878L, 55L)}));
    }

    private final Object m() {
        return new pq9("string:setting_reader_translate_qt_desc", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 40505L, 168L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 33561L, 124L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 35233L, 128L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 50877L, 172L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 45425L, 124L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 34525L, 124L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 35901L, 132L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 53909L, 180L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 32257L, 120L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 33941L, 120L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 35873L, 104L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 34541L, 132L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 33769L, 112L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 33817L, 136L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 34249L, 148L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 46705L, 180L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 53525L, 160L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 32969L, 120L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 46769L, 180L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 28905L, 104L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 28705L, 104L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 56745L, 132L)}));
    }

    private final Object n() {
        return new pq9("string:setting_reader_turn_page", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 41883L, 92L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 34635L, 76L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 36267L, 64L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 52387L, 92L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 46594L, 56L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 35583L, 72L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 36987L, 76L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 55647L, 108L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 33287L, 64L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 34935L, 64L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 36951L, 60L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 35583L, 64L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 34779L, 64L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 34867L, 72L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 35335L, 76L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 48259L, 100L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 55195L, 124L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 34007L, 68L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 48271L, 116L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 29703L, 48L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 29503L, 48L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 58090L, 72L)}));
    }

    private final Object o() {
        return new pq9("string:setting_reader_turn_page_anim", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 40881L, 85L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 33857L, 73L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 35545L, 69L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 51285L, 85L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 45717L, 65L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 34825L, 73L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 36213L, 73L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 54325L, 113L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 32553L, 69L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 34237L, 65L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 36177L, 85L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 34865L, 69L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 34061L, 65L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 34125L, 69L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 34573L, 81L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 47125L, 93L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 53945L, 113L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 33249L, 65L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 47193L, 109L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 29153L, 53L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 28953L, 53L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57057L, 81L)}));
    }

    private final Object p() {
        return new pq9("string:setting_display_dark_mode_time", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 33628L, 94L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 27864L, 82L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 29456L, 74L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 42148L, 138L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39530L, 62L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 28560L, 70L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 29648L, 86L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 45240L, 130L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 26812L, 74L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 28220L, 70L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 30312L, 78L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 28968L, 74L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 28292L, 70L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 27980L, 78L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 28276L, 90L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 38664L, 118L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 44708L, 122L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 27344L, 74L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 38720L, 118L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 24100L, 70L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 23892L, 70L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 49718L, 94L)}));
    }

    private final Object q() {
        return new pq9("string:setting_reader_turn_page_anim_desc", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 40730L, 150L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 33742L, 114L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 35418L, 126L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 51106L, 178L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 45606L, 110L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 34706L, 118L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 36090L, 122L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 54146L, 178L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 32434L, 118L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 34118L, 118L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 36034L, 142L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 34730L, 134L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 33938L, 122L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 34010L, 114L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 34454L, 118L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 46942L, 182L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 53742L, 202L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 33146L, 102L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 47006L, 186L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 29066L, 86L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 28866L, 86L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 56934L, 122L)}));
    }

    private final Object r() {
        return new pq9("string:setting_display_font_scale", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 34601L, 54L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 28677L, 54L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 30337L, 58L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 43433L, 94L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 40267L, 46L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 29361L, 58L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 30525L, 62L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 46465L, 74L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 27601L, 50L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 29021L, 54L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 31097L, 62L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 29833L, 54L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 29097L, 54L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 28781L, 58L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 29097L, 58L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 39757L, 70L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 45849L, 70L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 28141L, 50L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 39849L, 70L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 24829L, 50L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 24625L, 50L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 50683L, 70L)}));
    }

    private final Object s() {
        return new pq9("string:setting_reader_turn_page_desc", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 40967L, 173L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 33931L, 145L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 35615L, 141L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 51371L, 209L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 45783L, 109L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 34899L, 129L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 36287L, 133L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 54439L, 217L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 32623L, 129L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 34303L, 113L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 36263L, 125L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 34935L, 109L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 34127L, 125L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 34195L, 125L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 34655L, 133L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 47219L, 205L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 54059L, 257L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 33315L, 137L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 47303L, 185L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 29207L, 93L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 29007L, 93L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57139L, 141L)}));
    }

    private final Object t() {
        return new pq9("string:setting_reader_turn_page_group_animation", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 45893L, 76L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57281L, 84L)}));
    }

    private final Object u() {
        return new pq9("string:setting_reader_turn_page_group_interaction", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 45970L, 78L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57366L, 82L)}));
    }

    private final Object v() {
        return new pq9("string:setting_reader_turn_page_keyboard", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 41304L, 129L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 34196L, 97L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 35864L, 85L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 51752L, 137L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 46152L, 77L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 35156L, 89L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 36544L, 97L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 54864L, 177L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 32876L, 93L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 34532L, 85L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 36524L, 85L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 35164L, 85L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 34368L, 97L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 34436L, 85L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 34912L, 85L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 47600L, 149L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 54504L, 153L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 33596L, 89L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 47640L, 153L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 29396L, 65L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 29196L, 65L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57572L, 93L)}));
    }

    private final Object w() {
        return new pq9("string:setting_reader_turn_page_keyboard_desc", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 41141L, 162L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 34077L, 118L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 35757L, 106L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 51581L, 170L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 46049L, 102L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 35029L, 126L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 36421L, 122L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 54657L, 206L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 32753L, 122L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 34417L, 114L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 36389L, 134L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 35045L, 118L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 34253L, 114L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 34321L, 114L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 34789L, 122L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 47425L, 174L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 54317L, 186L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 33453L, 142L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 47489L, 150L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 29301L, 94L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 29101L, 94L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57449L, 122L)}));
    }

    private final Object x() {
        return new pq9("string:setting_reader_turn_page_sound", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 46350L, 58L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57794L, 70L)}));
    }

    private final Object y() {
        return new pq9("string:setting_reader_turn_page_sound_desc", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 41434L, 167L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 34294L, 131L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 35950L, 119L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 51890L, 191L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 46230L, 119L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 35246L, 135L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 36642L, 119L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 55042L, 219L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 32970L, 115L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 34618L, 127L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 36610L, 155L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 35250L, 147L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 34466L, 111L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 34522L, 127L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 34998L, 127L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 47750L, 187L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 54658L, 195L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 33686L, 107L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 47794L, 171L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 29462L, 99L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 29262L, 99L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57666L, 127L)}));
    }

    private final Object z() {
        return new pq9("string:setting_reader_turn_page_volume", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 41759L, 123L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 34527L, 107L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 36167L, 99L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 52243L, 143L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 46514L, 79L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 35495L, 87L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 36883L, 103L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 55439L, 207L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 33191L, 95L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 34847L, 87L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 36871L, 79L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 35499L, 83L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 34679L, 99L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 34767L, 99L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 35239L, 95L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 48095L, 163L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 55043L, 151L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 33907L, 99L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 48107L, 163L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 29635L, 67L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 29435L, 67L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57990L, 99L)}));
    }

    @Override // defpackage.vt4
    public final Object invoke() {
        switch (this.a) {
            case 0:
                return new pq9("string:setting_reader_show_progress", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 39564L, 84L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 32800L, 68L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 34488L, 68L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 49744L, 104L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 44688L, 64L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 33724L, 72L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 35104L, 84L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 52792L, 116L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 31516L, 68L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 33196L, 72L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 35160L, 64L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 33804L, 68L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 33060L, 64L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 33048L, 68L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 33424L, 76L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 45624L, 104L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 52324L, 124L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 32232L, 72L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 45656L, 104L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 28288L, 60L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 28092L, 60L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 55900L, 80L)}));
            case 1:
                return new pq9("string:setting_reader_text_to_speech", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 39832L, 73L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 33000L, 65L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 34680L, 65L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 50064L, 89L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 44884L, 65L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 33936L, 69L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 35324L, 69L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 53084L, 105L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 31700L, 57L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 33384L, 65L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 35344L, 77L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 34004L, 65L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 33240L, 69L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 33252L, 65L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 33640L, 69L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 45936L, 93L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 52704L, 89L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 32432L, 73L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 45972L, 89L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 28448L, 65L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 28252L, 61L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 56144L, 69L)}));
            case 2:
                return new pq9("string:setting_reader_text_to_speech_desc", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 39649L, 182L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 32869L, 130L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 34557L, 122L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 49849L, 214L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 44753L, 130L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 33797L, 138L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 35189L, 134L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 52909L, 174L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 31585L, 114L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 33269L, 114L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 35225L, 118L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 33873L, 130L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 33125L, 114L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 33117L, 134L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 33501L, 138L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 45729L, 206L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 52449L, 254L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 32305L, 126L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 45761L, 210L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 28349L, 98L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 28153L, 98L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 55981L, 162L)}));
            case 3:
                return new pq9("string:setting_display_dark_mode", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 33723L, 65L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 27947L, 53L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 29531L, 49L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 42287L, 77L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39593L, 45L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 28631L, 49L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 29735L, 53L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 45371L, 69L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 26887L, 49L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 28291L, 49L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 30391L, 57L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 29043L, 53L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 28363L, 53L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 28059L, 49L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 28367L, 49L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 38783L, 65L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 44831L, 61L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 27419L, 45L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 38839L, 61L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 24171L, 49L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 23963L, 49L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 49813L, 49L)}));
            case 4:
                return new pq9("string:setting_reader_touch_mode", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 39906L, 93L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 33066L, 81L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 34746L, 73L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 50154L, 121L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 44950L, 69L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 34006L, 77L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 35394L, 77L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 53190L, 117L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 31758L, 77L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 33450L, 73L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 35422L, 77L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 34070L, 69L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 33310L, 69L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 33318L, 69L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 33710L, 77L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 46030L, 117L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 52794L, 125L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 32506L, 81L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 46062L, 109L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 28514L, 57L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 28314L, 57L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 56214L, 85L)}));
            case 5:
                return new pq9("string:setting_reader_touch_turn_page", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 40000L, 86L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 33148L, 78L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 34820L, 70L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 50276L, 106L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 45020L, 62L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 34084L, 78L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 35472L, 78L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 53308L, 126L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 31836L, 74L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 33524L, 74L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 35500L, 74L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 34140L, 78L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 33380L, 74L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 33388L, 78L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 33788L, 70L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 46148L, 106L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 52920L, 114L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 32588L, 74L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 46172L, 130L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 28572L, 54L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 28372L, 54L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 56300L, 74L)}));
            case 6:
                return new pq9("string:setting_display_font", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 34656L, 56L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 28732L, 52L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 30396L, 64L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 43528L, 92L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 40314L, 48L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 29420L, 52L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 30588L, 52L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 46540L, 76L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 27652L, 48L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 29076L, 52L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 31160L, 60L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 29888L, 52L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 29152L, 56L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 28840L, 52L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 29156L, 48L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 39828L, 64L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 45920L, 76L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 28192L, 56L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 39920L, 64L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 24880L, 48L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 24676L, 48L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 50754L, 72L)}));
            case 7:
                return new pq9("string:setting_reader_translate_auto", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 40334L, 89L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 33418L, 65L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 35086L, 73L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 50674L, 109L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 45282L, 69L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 34370L, 85L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 35750L, 69L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 53734L, 85L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 32114L, 73L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 33802L, 65L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 35754L, 53L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 34414L, 57L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 33630L, 73L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 33670L, 73L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 34086L, 85L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 46530L, 81L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 53326L, 105L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 32838L, 61L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 46586L, 93L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 28786L, 53L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 28586L, 53L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 56582L, 77L)}));
            case 8:
                return b();
            case 9:
                return e();
            case 10:
                return f();
            case 11:
                return g();
            case 12:
                return m();
            case 13:
                return n();
            case 14:
                return o();
            case 15:
                return p();
            case 16:
                return q();
            case 17:
                return a();
            case 18:
                return s();
            case 19:
                return t();
            case 20:
                return u();
            case 21:
                return v();
            case 22:
                return w();
            case 23:
                return x();
            case 24:
                return y();
            case 25:
                return z();
            case 26:
                return A();
            case 27:
                return B();
            case 28:
                return r();
            default:
                return new pq9("string:setting_report", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 42119L, 42L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 34827L, 42L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 36427L, 34L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 52671L, 42L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 46754L, 34L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 35775L, 38L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 37179L, 38L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 55955L, 66L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 33475L, 38L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 35107L, 34L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 37123L, 50L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 35751L, 34L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 34943L, 34L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 35051L, 30L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 35527L, 34L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 48499L, 58L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 55543L, 62L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 34195L, 42L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 48539L, 38L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 29847L, 30L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 29647L, 30L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 58298L, 38L)}));
        }
    }
}
