package defpackage;

import java.util.Map;
import java.util.Set;
/* compiled from: r8-map-id-f559a6c9210f67746bd9ce87931ee85b676f3bda66e04dc5e85cb7e8eec71de1 */
/* renamed from: hr9  reason: default package */
/* loaded from: classes3.dex */
public abstract class hr9 {
    public static final Map a = o17.s(new yk8("a", "a"), new yk8("b", "bê"), new yk8("c", "xê"), new yk8("d", "đê"), new yk8("đ", "đê"), new yk8("e", "e"), new yk8("ê", "ê"), new yk8("f", "ép"), new yk8("g", "gờ"), new yk8("h", "hát"), new yk8("i", "i"), new yk8("j", "giây"), new yk8("k", "ca"), new yk8("l", "lờ"), new yk8("m", "mờ"), new yk8("n", "nờ"), new yk8("o", "ô"), new yk8("ô", "ô"), new yk8("ơ", "ơ"), new yk8("p", "pê"), new yk8("q", "qui"), new yk8("r", "rờ"), new yk8("s", "ét"), new yk8("t", "tê"), new yk8("u", "u"), new yk8("ư", "ư"), new yk8("v", "vê"), new yk8("w", "đắp liu"), new yk8("x", "ích"), new yk8("y", "y"), new yk8("z", "dét"));
    public static final Map b = o17.s(new yk8("km", "ki lô mét"), new yk8("dm", "đê xi mét"), new yk8("cm", "xen ti mét"), new yk8("mm", "mi li mét"), new yk8("nm", "na nô mét"), new yk8("µm", "mic rô mét"), new yk8("μm", "mic rô mét"), new yk8("m", "mét"), new yk8("kg", "ki lô gam"), new yk8("g", "gam"), new yk8("µg", "mic rô gam"), new yk8("mg", "mi li gam"), new yk8("km2", "ki lô mét vuông"), new yk8("m2", "mét vuông"), new yk8("cm2", "xen ti mét vuông"), new yk8("mm2", "mi li mét vuông"), new yk8("ha", "héc ta"), new yk8("km3", "ki lô mét khối"), new yk8("m3", "mét khối"), new yk8("cm3", "xen ti mét khối"), new yk8("mm3", "mi li mét khối"), new yk8("l", "lít"), new yk8("dl", "đê xi lít"), new yk8("ml", "mi li lít"), new yk8("hl", "héc tô lít"), new yk8("kw", "ki lô oát"), new yk8("mw", "mê ga oát"), new yk8("gw", "gi ga oát"), new yk8("kwh", "ki lô oát giờ"), new yk8("kWh", "ki lô oát giờ"), new yk8("mwh", "mê ga oát giờ"), new yk8("wh", "oát giờ"), new yk8("hz", "héc"), new yk8("khz", "ki lô héc"), new yk8("mhz", "mê ga héc"), new yk8("ghz", "gi ga héc"), new yk8("pa", a("pascal")), new yk8("kpa", a("kilopascal")), new yk8("mpa", a("megapascal")), new yk8("bar", a("bar")), new yk8("mbar", a("millibar")), new yk8("atm", a("atmosphere")), new yk8("psi", a("p s i")), new yk8("j", a("joule")), new yk8("kj", a("kilojoule")), new yk8("cal", a("calorie")), new yk8("kcal", a("kilocalorie")), new yk8("h", "giờ"), new yk8("p", "phút"), new yk8("s", "giây"), new yk8("sqm", "mét vuông"), new yk8("cum", "mét khối"), new yk8("gb", a("gigabyte")), new yk8("mb", a("megabyte")), new yk8("kb", a("kilobyte")), new yk8("tb", a("terabyte")), new yk8("db", a("decibel")), new yk8("oz", a("ounce")), new yk8("lb", a("pound")), new yk8("lbs", a("pounds")), new yk8("ft", a("feet")), new yk8("in", a("inch")), new yk8("dpi", a("d p i")), new yk8("ph", "pê hát"), new yk8("gbps", a("gigabits per second")), new yk8("mbps", a("megabits per second")), new yk8("kbps", a("kilobits per second")), new yk8("gallon", a("gallon")), new yk8("mol", "mol"), new yk8("ms", "mi li giây"), new yk8("M", "triệu"), new yk8("B", "tỷ"));
    public static final Map c = o17.s(new yk8("usd", a("u s d")), new yk8("vnd", "việt nam đồng"), new yk8("vnđ", "việt nam đồng"), new yk8("đ", "đồng"), new yk8("v n d", "việt nam đồng"), new yk8("v n đ", "việt nam đồng"), new yk8("€", a("euro")), new yk8("euro", a("euro")), new yk8("eur", a("euro")), new yk8("¥", "yên"), new yk8("yên", "yên"), new yk8("jpy", "yên"), new yk8("%", "phần trăm"));
    public static final Map d = o17.s(new yk8("CĐV", "cổ động viên"), new yk8("HĐND", "hội đồng nhân dân"), new yk8("HĐQT", "hội đồng quản trị"), new yk8("TAND", "toàn án nhân dân"), new yk8("BHXH", "bảo hiểm xã hội"), new yk8("BHTN", "bảo hiểm thất nghiệp"), new yk8("TP.HCM", "thành phố hồ chí minh"), new yk8("VN", "việt nam"), new yk8("UBND", "uỷ ban nhân dân"), new yk8("TP", "thành phố"), new yk8("HCM", "hồ chí minh"), new yk8("HN", "hà nội"), new yk8("BTC", "ban tổ chức"), new yk8("CLB", "câu lạc bộ"), new yk8("HTX", "hợp tác xã"), new yk8("NXB", "nhà xuất bản"), new yk8("TW", "trung ương"), new yk8("CSGT", "cảnh sát giao thông"), new yk8("LHQ", "liên hợp quốc"), vae.n("THCS", "trung học cơ sở"), vae.n("THPT", "trung học phổ thông"), vae.n("ĐH", "đại học"), vae.n("HLV", "huấn luyện viên"), vae.n("GS", "giáo sư"), vae.n("TS", "tiến sĩ"), vae.n("TNHH", "trách nhiệm hữu hạn"), vae.n("VĐV", "vận động viên"), vae.n("TPHCM", "thành phố hồ chí minh"), vae.n("PGS", "phó giáo sư"), vae.n("SP500", "ét pê năm trăm"), vae.n("PGS.TS", "phó giáo sư tiến sĩ"), vae.n("GS.TS", "giáo sư tiến sĩ"), vae.n("ThS", "thạc sĩ"), vae.n("BS", "bác sĩ"), vae.n("UAE", "u a e"), vae.n("CUDA", "cu đa"));
    public static final Map e = o17.s(vae.n("JSON", a("j son")), vae.n("VRAM", a("v ram")), vae.n("NVIDIA", a("n v d a")), vae.n("VN-Index", a("v n").concat(" index")), vae.n("MS DOS", a("m s dos")), vae.n("MS-DOS", a("m s dos")), vae.n("B2B", a("b two b")), vae.n("MI5", a("m i five")), vae.n("MI6", a("m i six")), vae.n("2FA", a("two f a")), vae.n("TX-0", a("t x zero")), vae.n("IPv6", a("i p v").concat(" sáu")), vae.n("IPv4", a("i p v").concat(" bốn")), vae.n("Washington D.C", a("washington d c")), vae.n("Washington DC", a("washington d c")), vae.n("HCN", "hát xê nờ"), vae.n("HF", "hát ép"), vae.n("KI", "ca i"), vae.n("KOH", "ca ô hát"));
    public static final Map f = o17.s(vae.n("com", "com"), vae.n("vn", a("v n")), vae.n("net", "nét"), vae.n("org", "o rờ gờ"), vae.n("edu", a("edu")), vae.n("gov", "gờ o vê"), vae.n("io", a("i o")), vae.n("biz", "biz"), vae.n("info", "info"));
    public static final Map g = o17.s(vae.n("$", a("u s d")), vae.n("€", a("euro")), vae.n("¥", "yên"), vae.n("£", a("pound")), vae.n("₩", "won"));
    public static final Map h = o17.s(vae.n('I', 1), vae.n('V', 5), vae.n('X', 10), vae.n('L', 50), vae.n('C', 100), vae.n('D', 500), vae.n('M', 1000));
    public static final Map i = o17.s(vae.n("v.v", " vân vân"), vae.n("v/v", " về việc"), vae.n("đ/c", "địa chỉ"));
    public static final Map j = o17.s(vae.n('&', " và "), vae.n('+', " cộng "), vae.n('=', " bằng "), vae.n('#', " thăng "), vae.n('>', " lớn hơn "), vae.n('<', " nhỏ hơn "), vae.n((char) 8805, " lớn hơn hoặc bằng "), vae.n((char) 8804, " nhỏ hơn hoặc bằng "), vae.n((char) 177, " cộng trừ "), vae.n((char) 8776, " xấp xỉ "), vae.n('/', " trên "), vae.n((char) 8594, " đến "), vae.n((char) 247, " chia "), vae.n('*', " sao "), vae.n((char) 215, " nhân "), vae.n('^', " mũ "), vae.n('~', " khoảng "), vae.n('%', " phần trăm "), vae.n('$', " đô la "), vae.n((char) 8364, " ê rô "), vae.n((char) 163, " bảng "), vae.n((char) 165, " yên "), vae.n((char) 8361, " won "), vae.n((char) 8365, " kíp "), vae.n((char) 8369, " bê xô "), vae.n((char) 3647, " bạc "), vae.n((char) 937, " ôm "), vae.n('@', " a còng "), vae.n((char) 8800, " khác "), vae.n((char) 8704, " với mọi "), vae.n((char) 8719, " tích "), vae.n((char) 8712, " thuộc "), vae.n((char) 8721, " tổng "), vae.n((char) 8745, " giao "), vae.n((char) 8746, " hội "), vae.n((char) 172, " phủ định "), vae.n((char) 8734, " vô cùng "), vae.n((char) 945, " an pha "), vae.n((char) 946, " bê ta "), vae.n((char) 947, " ga ma "), vae.n((char) 948, " đen ta "), vae.n((char) 949, " ép si lon "), vae.n((char) 1013, " thuộc "), vae.n((char) 950, " de ta "), vae.n((char) 951, " ê ta "), vae.n((char) 952, " thê ta "), vae.n((char) 953, " i ô ta "), vae.n((char) 954, " cáp ba "), vae.n((char) 955, " lam đa "), vae.n((char) 7463, " và "), vae.n((char) 956, " muy "), vae.n((char) 916, " đen ta "), vae.n((char) 957, " nu "), vae.n((char) 958, " xi xi "), vae.n((char) 959, " o mi ron "), vae.n((char) 960, " pi "), vae.n((char) 961, " ro "), vae.n((char) 963, " xích ma "), vae.n((char) 964, " tao "), vae.n((char) 965, " úp si lon "), vae.n((char) 966, " phi "), vae.n((char) 967, " chi "), vae.n((char) 968, " si "), vae.n((char) 969, " ô me ga "), vae.n((char) 169, " bản quyền "), vae.n((char) 189, " một phần hai "), vae.n((char) 188, " một phần tư "), vae.n((char) 190, " ba phần tư "), vae.n((char) 8531, " một phần ba "), vae.n((char) 8532, " hai phần ba "), vae.n((char) 8533, " một phần năm "), vae.n((char) 8534, " hai phần năm "), vae.n((char) 8535, " ba phần năm "), vae.n((char) 8536, " bốn phần năm "), vae.n((char) 8538, " năm phần sáu "));
    public static final Map k = o17.s(vae.n((char) 8304, " không "), vae.n((char) 185, " một "), vae.n((char) 178, " bình phương "), vae.n((char) 179, " lập phương "), vae.n((char) 8308, " bốn "), vae.n((char) 8309, " năm "), vae.n((char) 8310, " sáu "), vae.n((char) 8311, " bảy "), vae.n((char) 8312, " tám "), vae.n((char) 8313, " chín "));
    public static final Map l = o17.s(vae.n((char) 8320, " không "), vae.n((char) 8321, " một "), vae.n((char) 8322, " hai "), vae.n((char) 8323, " ba "), vae.n((char) 8324, " bốn "), vae.n((char) 8325, " năm "), vae.n((char) 8326, " sáu "), vae.n((char) 8327, " bảy "), vae.n((char) 8328, " tám "), vae.n((char) 8329, " chín "));
    public static final Set m = b00.F0(new String[]{"UNESCO", "NASA", "NATO", "ASEAN", "OPEC", "SARS", "FIFA", "UNIC", "RAM", "VRAM", "COVID", "IELTS", "STEM", "SWAT", "SEAL", "WASP", "COBOL", "BASIC", "OLED", "COVAX", "BRICS", "APEC", "VUCA", "PERMA", "DINK", "MENA", "EPIC", "OASIS", "BASE", "DART", "IDEA", "CHAOS", "SMART", "FANG", "BLEU", "REST", "ERROR", "SELECT", "FROM", "WHERE", "ORDER", "BY", "LIMIT", "OFFSET", "GROUP", "HAVING", "JOIN", "LEFT", "RIGHT", "INNER", "OUTER", "ON", "AS", "AND", "OR", "NOT", "IN", "BETWEEN", "LIKE", "IS", "NULL", "TRUE", "FALSE", "CASE", "WHEN", "THEN", "ELSE", "END", "UNION", "INTERSECT", "EXCEPT", "DESC"});
    public static final Map n = o17.s(vae.n("gmail.com", a("gmail").concat(" chấm com")), vae.n("yahoo.com", a("yahoo").concat(" chấm com")), vae.n("yahoo.com.vn", a("yahoo") + " chấm com chấm " + a("v n")), vae.n("outlook.com", a("outlook").concat(" chấm com")), vae.n("hotmail.com", a("hotmail").concat(" chấm com")), vae.n("icloud.com", a("icloud").concat(" chấm com")), vae.n("fpt.vn", a("f p t") + " chấm " + a("v n")), vae.n("fpt.com.vn", a("f p t") + " chấm com chấm " + a("v n")));
    public static final mfb o = ipe.y(new pa9(12));
    public static final Set p = b00.F0(new String[]{"vào", "ngày", "hôm", "hôm nay", "hôm qua", "hôm kia", "mai", "ngày mai", "ngày kia", "sinh", "sinh nhật", "kỷ niệm", "lễ", "tết", "diễn ra", "tổ chức", "thứ", "tuần", "tháng", "năm"});
    public static final Set q = b00.F0(new String[]{"cộng", "trừ", "nhân", "chia", "bằng", "sin", "cos", "tan", "log", "sqrt", "xác suất", "tỷ lệ", "tỉ lệ"});

    public static String a(String str) {
        return hl5.n("__start_en__", str, "__end_en__");
    }
}
