package defpackage;
/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* compiled from: r8-map-id-f559a6c9210f67746bd9ce87931ee85b676f3bda66e04dc5e85cb7e8eec71de1 */
/* renamed from: ifc  reason: default package */
/* loaded from: classes.dex */
public abstract class ifc {
    public static final wdc A0;
    public static final ucc B0;
    public static final ndc C;
    public static final wcc C0;
    public static final hec D;
    public static final gdc D0;
    public static final nec E;
    public static final xdc E0;
    public static final eec F;
    public static final ydc F0;
    public static final hfc G;
    public static final vcc G0;
    public static final bec H;
    public static final idc H0;
    public static final gfc I;
    public static final ycc I0;
    public static final mec J;
    public static final hdc J0;
    public static final gec K;
    public static final zdc K0;
    public static final fec L;
    public static final aec L0;
    public static final kec M;
    public static final xcc M0;
    public static final jec N;
    public static final kdc N0;
    public static final iec O;
    public static final ldc O0;
    public static final efc P;
    public static final /* synthetic */ ifc[] P0;
    public static final vec Q;
    public static final uec R;
    public static final wec S;
    public static final xec T;
    public static final yec U;
    public static final zec V;
    public static final afc W;
    public static final dfc X;
    public static final cfc Y;
    public static final bfc Z;
    public static final d38 a;
    public static final pec a0;
    public static final char[] b;
    public static final qec b0;
    public static final char[] c;
    public static final rec c0;
    public static final udc d;
    public static final sec d0;
    public static final mdc e;
    public static final tec e0;
    public static final lec f;
    public static final oec f0;
    public static final ddc g0;
    public static final zcc h0;
    public static final scc i0;
    public static final edc j0;
    public static final adc k0;
    public static final bdc l0;
    public static final cdc m0;
    public static final tcc n0;
    public static final ffc o0;
    public static final jdc p0;
    public static final cec q0;
    public static final dec r0;
    public static final sdc s0;
    public static final tdc t0;
    public static final odc u0;
    public static final rdc v0;
    public static final pdc w0;
    public static final qdc x0;
    public static final vdc y0;
    public static final fdc z0;

    static {
        udc udcVar = new udc();
        d = udcVar;
        mdc mdcVar = new mdc();
        e = mdcVar;
        lec lecVar = new lec();
        f = lecVar;
        ndc ndcVar = new ndc();
        C = ndcVar;
        hec hecVar = new hec();
        D = hecVar;
        nec necVar = new nec();
        E = necVar;
        eec eecVar = new eec();
        F = eecVar;
        hfc hfcVar = new hfc();
        G = hfcVar;
        bec becVar = new bec();
        H = becVar;
        gfc gfcVar = new gfc();
        I = gfcVar;
        mec mecVar = new mec();
        J = mecVar;
        gec gecVar = new gec();
        K = gecVar;
        fec fecVar = new fec();
        L = fecVar;
        kec kecVar = new kec();
        M = kecVar;
        jec jecVar = new jec();
        N = jecVar;
        iec iecVar = new iec();
        O = iecVar;
        efc efcVar = new efc();
        P = efcVar;
        vec vecVar = new vec();
        Q = vecVar;
        uec uecVar = new uec();
        R = uecVar;
        wec wecVar = new wec();
        S = wecVar;
        xec xecVar = new xec();
        T = xecVar;
        yec yecVar = new yec();
        U = yecVar;
        zec zecVar = new zec();
        V = zecVar;
        afc afcVar = new afc();
        W = afcVar;
        dfc dfcVar = new dfc();
        X = dfcVar;
        cfc cfcVar = new cfc();
        Y = cfcVar;
        bfc bfcVar = new bfc();
        Z = bfcVar;
        pec pecVar = new pec();
        a0 = pecVar;
        qec qecVar = new qec();
        b0 = qecVar;
        rec recVar = new rec();
        c0 = recVar;
        sec secVar = new sec();
        d0 = secVar;
        tec tecVar = new tec();
        e0 = tecVar;
        oec oecVar = new oec();
        f0 = oecVar;
        ddc ddcVar = new ddc();
        g0 = ddcVar;
        zcc zccVar = new zcc();
        h0 = zccVar;
        scc sccVar = new scc();
        i0 = sccVar;
        edc edcVar = new edc();
        j0 = edcVar;
        adc adcVar = new adc();
        k0 = adcVar;
        bdc bdcVar = new bdc();
        l0 = bdcVar;
        cdc cdcVar = new cdc();
        m0 = cdcVar;
        tcc tccVar = new tcc();
        n0 = tccVar;
        ffc ffcVar = new ffc();
        o0 = ffcVar;
        jdc jdcVar = new jdc();
        p0 = jdcVar;
        cec cecVar = new cec();
        q0 = cecVar;
        dec decVar = new dec();
        r0 = decVar;
        sdc sdcVar = new sdc();
        s0 = sdcVar;
        tdc tdcVar = new tdc();
        t0 = tdcVar;
        odc odcVar = new odc();
        u0 = odcVar;
        rdc rdcVar = new rdc();
        v0 = rdcVar;
        pdc pdcVar = new pdc();
        w0 = pdcVar;
        qdc qdcVar = new qdc();
        x0 = qdcVar;
        vdc vdcVar = new vdc();
        y0 = vdcVar;
        fdc fdcVar = new fdc();
        z0 = fdcVar;
        wdc wdcVar = new wdc();
        A0 = wdcVar;
        ucc uccVar = new ucc();
        B0 = uccVar;
        wcc wccVar = new wcc();
        C0 = wccVar;
        gdc gdcVar = new gdc();
        D0 = gdcVar;
        xdc xdcVar = new xdc();
        E0 = xdcVar;
        ydc ydcVar = new ydc();
        F0 = ydcVar;
        vcc vccVar = new vcc();
        G0 = vccVar;
        idc idcVar = new idc();
        H0 = idcVar;
        ycc yccVar = new ycc();
        I0 = yccVar;
        hdc hdcVar = new hdc();
        J0 = hdcVar;
        zdc zdcVar = new zdc();
        K0 = zdcVar;
        aec aecVar = new aec();
        L0 = aecVar;
        xcc xccVar = new xcc();
        M0 = xccVar;
        kdc kdcVar = new kdc();
        N0 = kdcVar;
        ldc ldcVar = new ldc();
        O0 = ldcVar;
        P0 = new ifc[]{udcVar, mdcVar, lecVar, ndcVar, hecVar, necVar, eecVar, hfcVar, becVar, gfcVar, mecVar, gecVar, fecVar, kecVar, jecVar, iecVar, efcVar, vecVar, uecVar, wecVar, xecVar, yecVar, zecVar, afcVar, dfcVar, cfcVar, bfcVar, pecVar, qecVar, recVar, secVar, tecVar, oecVar, ddcVar, zccVar, sccVar, edcVar, adcVar, bdcVar, cdcVar, tccVar, ffcVar, jdcVar, cecVar, decVar, sdcVar, tdcVar, odcVar, rdcVar, pdcVar, qdcVar, vdcVar, fdcVar, wdcVar, uccVar, wccVar, gdcVar, xdcVar, ydcVar, vccVar, idcVar, yccVar, hdcVar, zdcVar, aecVar, xccVar, kdcVar, ldcVar};
        a = new d38(6);
        b = new char[]{'\t', '\n', '\f', '\r', ' ', '\"', '\'', '/', '<', '=', '>', '?'};
        c = new char[]{0, '\t', '\n', '\f', '\r', ' ', '\"', '&', '\'', '<', '=', '>', '`'};
    }

    public static ifc valueOf(String str) {
        return (ifc) Enum.valueOf(ifc.class, str);
    }

    public static ifc[] values() {
        return (ifc[]) P0.clone();
    }

    public abstract void a(rcc rccVar, vc1 vc1Var);
}
