package defpackage;
/* compiled from: r8-map-id-f559a6c9210f67746bd9ce87931ee85b676f3bda66e04dc5e85cb7e8eec71de1 */
/* renamed from: ije  reason: default package */
/* loaded from: classes.dex */
public final class ije implements e78 {
    public static final ije a = new Object();
    public static final ac4 b = new ac4(a82.q(eub.q(e8e.class, new h4e(1))), "systemInfo");
    public static final ac4 c = new ac4(a82.q(eub.q(e8e.class, new h4e(2))), "eventName");
    public static final ac4 d = new ac4(a82.q(eub.q(e8e.class, new h4e(37))), "isThickClient");
    public static final ac4 e = new ac4(a82.q(eub.q(e8e.class, new h4e(61))), "clientType");
    public static final ac4 f = new ac4(a82.q(eub.q(e8e.class, new h4e(3))), "modelDownloadLogEvent");
    public static final ac4 g = new ac4(a82.q(eub.q(e8e.class, new h4e(20))), "customModelLoadLogEvent");
    public static final ac4 h = new ac4(a82.q(eub.q(e8e.class, new h4e(4))), "customModelInferenceLogEvent");
    public static final ac4 i = new ac4(a82.q(eub.q(e8e.class, new h4e(29))), "customModelCreateLogEvent");
    public static final ac4 j = new ac4(a82.q(eub.q(e8e.class, new h4e(5))), "onDeviceFaceDetectionLogEvent");
    public static final ac4 k = new ac4(a82.q(eub.q(e8e.class, new h4e(59))), "onDeviceFaceLoadLogEvent");
    public static final ac4 l = new ac4(a82.q(eub.q(e8e.class, new h4e(6))), "onDeviceTextDetectionLogEvent");
    public static final ac4 m = new ac4(a82.q(eub.q(e8e.class, new h4e(79))), "onDeviceTextDetectionLoadLogEvent");
    public static final ac4 n = new ac4(a82.q(eub.q(e8e.class, new h4e(7))), "onDeviceBarcodeDetectionLogEvent");
    public static final ac4 o = new ac4(a82.q(eub.q(e8e.class, new h4e(58))), "onDeviceBarcodeLoadLogEvent");
    public static final ac4 p = new ac4(a82.q(eub.q(e8e.class, new h4e(48))), "onDeviceImageLabelCreateLogEvent");
    public static final ac4 q = new ac4(a82.q(eub.q(e8e.class, new h4e(49))), "onDeviceImageLabelLoadLogEvent");
    public static final ac4 r = new ac4(a82.q(eub.q(e8e.class, new h4e(18))), "onDeviceImageLabelDetectionLogEvent");
    public static final ac4 s = new ac4(a82.q(eub.q(e8e.class, new h4e(26))), "onDeviceObjectCreateLogEvent");
    public static final ac4 t = new ac4(a82.q(eub.q(e8e.class, new h4e(27))), "onDeviceObjectLoadLogEvent");
    public static final ac4 u = new ac4(a82.q(eub.q(e8e.class, new h4e(28))), "onDeviceObjectInferenceLogEvent");
    public static final ac4 v = new ac4(a82.q(eub.q(e8e.class, new h4e(44))), "onDevicePoseDetectionLogEvent");
    public static final ac4 w = new ac4(a82.q(eub.q(e8e.class, new h4e(45))), "onDeviceSegmentationLogEvent");
    public static final ac4 x = new ac4(a82.q(eub.q(e8e.class, new h4e(19))), "onDeviceSmartReplyLogEvent");
    public static final ac4 y = new ac4(a82.q(eub.q(e8e.class, new h4e(21))), "onDeviceLanguageIdentificationLogEvent");
    public static final ac4 z = new ac4(a82.q(eub.q(e8e.class, new h4e(22))), "onDeviceTranslationLogEvent");
    public static final ac4 A = new ac4(a82.q(eub.q(e8e.class, new h4e(8))), "cloudFaceDetectionLogEvent");
    public static final ac4 B = new ac4(a82.q(eub.q(e8e.class, new h4e(9))), "cloudCropHintDetectionLogEvent");
    public static final ac4 C = new ac4(a82.q(eub.q(e8e.class, new h4e(10))), "cloudDocumentTextDetectionLogEvent");
    public static final ac4 D = new ac4(a82.q(eub.q(e8e.class, new h4e(11))), "cloudImagePropertiesDetectionLogEvent");
    public static final ac4 E = new ac4(a82.q(eub.q(e8e.class, new h4e(12))), "cloudImageLabelDetectionLogEvent");
    public static final ac4 F = new ac4(a82.q(eub.q(e8e.class, new h4e(13))), "cloudLandmarkDetectionLogEvent");
    public static final ac4 G = new ac4(a82.q(eub.q(e8e.class, new h4e(14))), "cloudLogoDetectionLogEvent");
    public static final ac4 H = new ac4(a82.q(eub.q(e8e.class, new h4e(15))), "cloudSafeSearchDetectionLogEvent");
    public static final ac4 I = new ac4(a82.q(eub.q(e8e.class, new h4e(16))), "cloudTextDetectionLogEvent");
    public static final ac4 J = new ac4(a82.q(eub.q(e8e.class, new h4e(17))), "cloudWebSearchDetectionLogEvent");
    public static final ac4 K = new ac4(a82.q(eub.q(e8e.class, new h4e(23))), "automlImageLabelingCreateLogEvent");
    public static final ac4 L = new ac4(a82.q(eub.q(e8e.class, new h4e(24))), "automlImageLabelingLoadLogEvent");
    public static final ac4 M = new ac4(a82.q(eub.q(e8e.class, new h4e(25))), "automlImageLabelingInferenceLogEvent");
    public static final ac4 N = new ac4(a82.q(eub.q(e8e.class, new h4e(39))), "isModelDownloadedLogEvent");
    public static final ac4 O = new ac4(a82.q(eub.q(e8e.class, new h4e(40))), "deleteModelLogEvent");
    public static final ac4 P = new ac4(a82.q(eub.q(e8e.class, new h4e(30))), "aggregatedAutomlImageLabelingInferenceLogEvent");
    public static final ac4 Q = new ac4(a82.q(eub.q(e8e.class, new h4e(31))), "aggregatedCustomModelInferenceLogEvent");
    public static final ac4 R = new ac4(a82.q(eub.q(e8e.class, new h4e(32))), "aggregatedOnDeviceFaceDetectionLogEvent");
    public static final ac4 S = new ac4(a82.q(eub.q(e8e.class, new h4e(33))), "aggregatedOnDeviceBarcodeDetectionLogEvent");
    public static final ac4 T = new ac4(a82.q(eub.q(e8e.class, new h4e(34))), "aggregatedOnDeviceImageLabelDetectionLogEvent");
    public static final ac4 U = new ac4(a82.q(eub.q(e8e.class, new h4e(35))), "aggregatedOnDeviceObjectInferenceLogEvent");
    public static final ac4 V = new ac4(a82.q(eub.q(e8e.class, new h4e(36))), "aggregatedOnDeviceTextDetectionLogEvent");
    public static final ac4 W = new ac4(a82.q(eub.q(e8e.class, new h4e(46))), "aggregatedOnDevicePoseDetectionLogEvent");
    public static final ac4 X = new ac4(a82.q(eub.q(e8e.class, new h4e(47))), "aggregatedOnDeviceSegmentationLogEvent");
    public static final ac4 Y = new ac4(a82.q(eub.q(e8e.class, new h4e(69))), "pipelineAccelerationInferenceEvents");
    public static final ac4 Z = new ac4(a82.q(eub.q(e8e.class, new h4e(42))), "remoteConfigLogEvent");
    public static final ac4 a0 = new ac4(a82.q(eub.q(e8e.class, new h4e(50))), "inputImageConstructionLogEvent");
    public static final ac4 b0 = new ac4(a82.q(eub.q(e8e.class, new h4e(51))), "leakedHandleEvent");
    public static final ac4 c0 = new ac4(a82.q(eub.q(e8e.class, new h4e(52))), "cameraSourceLogEvent");
    public static final ac4 d0 = new ac4(a82.q(eub.q(e8e.class, new h4e(53))), "imageLabelOptionalModuleLogEvent");
    public static final ac4 e0 = new ac4(a82.q(eub.q(e8e.class, new h4e(54))), "languageIdentificationOptionalModuleLogEvent");
    public static final ac4 f0 = new ac4(a82.q(eub.q(e8e.class, new h4e(60))), "faceDetectionOptionalModuleLogEvent");
    public static final ac4 g0 = new ac4(a82.q(eub.q(e8e.class, new h4e(55))), "nlClassifierOptionalModuleLogEvent");
    public static final ac4 h0 = new ac4(a82.q(eub.q(e8e.class, new h4e(56))), "nlClassifierClientLibraryLogEvent");
    public static final ac4 i0 = new ac4(a82.q(eub.q(e8e.class, new h4e(57))), "accelerationAllowlistLogEvent");
    public static final ac4 j0 = new ac4(a82.q(eub.q(e8e.class, new h4e(62))), "toxicityDetectionCreateEvent");
    public static final ac4 k0 = new ac4(a82.q(eub.q(e8e.class, new h4e(63))), "toxicityDetectionLoadEvent");
    public static final ac4 l0 = new ac4(a82.q(eub.q(e8e.class, new h4e(64))), "toxicityDetectionInferenceEvent");
    public static final ac4 m0 = new ac4(a82.q(eub.q(e8e.class, new h4e(65))), "barcodeDetectionOptionalModuleLogEvent");
    public static final ac4 n0 = new ac4(a82.q(eub.q(e8e.class, new h4e(66))), "customImageLabelOptionalModuleLogEvent");
    public static final ac4 o0 = new ac4(a82.q(eub.q(e8e.class, new h4e(67))), "codeScannerScanApiEvent");
    public static final ac4 p0 = new ac4(a82.q(eub.q(e8e.class, new h4e(68))), "codeScannerOptionalModuleEvent");
    public static final ac4 q0 = new ac4(a82.q(eub.q(e8e.class, new h4e(70))), "onDeviceExplicitContentCreateLogEvent");
    public static final ac4 r0 = new ac4(a82.q(eub.q(e8e.class, new h4e(71))), "onDeviceExplicitContentLoadLogEvent");
    public static final ac4 s0 = new ac4(a82.q(eub.q(e8e.class, new h4e(72))), "onDeviceExplicitContentInferenceLogEvent");
    public static final ac4 t0 = new ac4(a82.q(eub.q(e8e.class, new h4e(73))), "aggregatedOnDeviceExplicitContentLogEvent");
    public static final ac4 u0 = new ac4(a82.q(eub.q(e8e.class, new h4e(74))), "onDeviceSelfieFaceCreateLogEvent");
    public static final ac4 v0 = new ac4(a82.q(eub.q(e8e.class, new h4e(75))), "onDeviceSelfieFaceLoadLogEvent");
    public static final ac4 w0 = new ac4(a82.q(eub.q(e8e.class, new h4e(76))), "onDeviceSelfieFaceLogEvent");
    public static final ac4 x0 = new ac4(a82.q(eub.q(e8e.class, new h4e(77))), "aggregatedOnDeviceSelfieFaceLogEvent");
    public static final ac4 y0 = new ac4(a82.q(eub.q(e8e.class, new h4e(78))), "smartReplyOptionalModuleLogEvent");

    @Override // defpackage.ws3
    public final void a(Object obj, Object obj2) {
        ite iteVar = (ite) obj;
        f78 f78Var = (f78) obj2;
        f78Var.a(b, iteVar.a);
        f78Var.a(c, iteVar.b);
        f78Var.a(d, null);
        f78Var.a(e, iteVar.c);
        f78Var.a(f, null);
        f78Var.a(g, null);
        f78Var.a(h, null);
        f78Var.a(i, null);
        f78Var.a(j, null);
        f78Var.a(k, null);
        f78Var.a(l, null);
        f78Var.a(m, null);
        f78Var.a(n, null);
        f78Var.a(o, null);
        f78Var.a(p, null);
        f78Var.a(q, null);
        f78Var.a(r, null);
        f78Var.a(s, null);
        f78Var.a(t, null);
        f78Var.a(u, null);
        f78Var.a(v, null);
        f78Var.a(w, null);
        f78Var.a(x, null);
        f78Var.a(y, iteVar.d);
        f78Var.a(z, null);
        f78Var.a(A, null);
        f78Var.a(B, null);
        f78Var.a(C, null);
        f78Var.a(D, null);
        f78Var.a(E, null);
        f78Var.a(F, null);
        f78Var.a(G, null);
        f78Var.a(H, null);
        f78Var.a(I, null);
        f78Var.a(J, null);
        f78Var.a(K, null);
        f78Var.a(L, null);
        f78Var.a(M, null);
        f78Var.a(N, null);
        f78Var.a(O, null);
        f78Var.a(P, null);
        f78Var.a(Q, null);
        f78Var.a(R, null);
        f78Var.a(S, null);
        f78Var.a(T, null);
        f78Var.a(U, null);
        f78Var.a(V, null);
        f78Var.a(W, null);
        f78Var.a(X, null);
        f78Var.a(Y, null);
        f78Var.a(Z, null);
        f78Var.a(a0, null);
        f78Var.a(b0, null);
        f78Var.a(c0, null);
        f78Var.a(d0, null);
        f78Var.a(e0, null);
        f78Var.a(f0, null);
        f78Var.a(g0, null);
        f78Var.a(h0, null);
        f78Var.a(i0, null);
        f78Var.a(j0, null);
        f78Var.a(k0, null);
        f78Var.a(l0, null);
        f78Var.a(m0, null);
        f78Var.a(n0, null);
        f78Var.a(o0, null);
        f78Var.a(p0, null);
        f78Var.a(q0, null);
        f78Var.a(r0, null);
        f78Var.a(s0, null);
        f78Var.a(t0, null);
        f78Var.a(u0, null);
        f78Var.a(v0, null);
        f78Var.a(w0, null);
        f78Var.a(x0, null);
        f78Var.a(y0, null);
    }
}
