package defpackage;
/* compiled from: r8-map-id-f559a6c9210f67746bd9ce87931ee85b676f3bda66e04dc5e85cb7e8eec71de1 */
/* renamed from: n2b  reason: default package */
/* loaded from: classes3.dex */
public final /* synthetic */ class n2b implements vt4 {
    public final /* synthetic */ int a;

    private final Object a() {
        return new pq9("string:error_empty_content_description", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 17614L, 155L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 14826L, 143L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 15588L, 139L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 22522L, 223L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 23306L, 119L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 15334L, 123L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 15910L, 131L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 24182L, 239L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 14188L, 119L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 15114L, 131L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 16222L, 167L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 15378L, 147L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 15168L, 123L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 14902L, 119L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 15178L, 115L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 20606L, 203L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 23686L, 243L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 14602L, 131L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 20674L, 183L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 12942L, 107L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 12778L, 103L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30441L, 139L)}));
    }

    private final Object b() {
        return new pq9("string:error_empty_search", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 17993L, 86L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 15173L, 66L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 15923L, 62L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 23133L, 94L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 23597L, 50L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 15661L, 66L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 16241L, 58L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 24805L, 102L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 14507L, 58L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 15453L, 62L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 16665L, 70L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 15765L, 66L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 15475L, 62L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 15193L, 58L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 15517L, 66L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 21109L, 82L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 24261L, 74L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 14953L, 54L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 21153L, 86L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 13217L, 50L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 13061L, 50L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30824L, 70L)}));
    }

    private final Object e() {
        return new pq9("string:error_empty_search_description", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 17834L, 158L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 15018L, 154L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 15772L, 150L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 22834L, 298L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 23470L, 126L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 15510L, 150L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 16090L, 150L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 24514L, 290L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 14360L, 146L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 15298L, 154L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 16466L, 198L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 15590L, 174L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 15336L, 138L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 15070L, 122L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 15342L, 174L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 20878L, 230L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 24006L, 254L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 14782L, 170L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 20926L, 226L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 13098L, 118L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 12930L, 130L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30641L, 182L)}));
    }

    private final Object f() {
        return new pq9("string:error_extension_not_found", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 18080L, 181L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 15240L, 149L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 15986L, 165L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 23228L, 241L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 23648L, 145L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 15728L, 149L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 16300L, 149L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 24908L, 309L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 14566L, 141L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 15516L, 149L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 16736L, 189L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 15832L, 177L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 15538L, 165L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 15252L, 141L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 15584L, 137L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 21192L, 197L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 24336L, 325L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 15008L, 141L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 21240L, 209L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 13268L, 129L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 13112L, 121L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30895L, 173L)}));
    }

    private final Object g() {
        return new pq9("string:error_load_book", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 18430L, 67L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 15502L, 51L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 16292L, 67L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 23726L, 111L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 23914L, 51L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 16022L, 67L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 16594L, 71L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 25506L, 103L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 14832L, 59L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 15806L, 71L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 17074L, 67L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 16162L, 75L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 15812L, 51L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 15522L, 67L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 15866L, 79L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 21590L, 91L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 24894L, 107L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 15282L, 51L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 21610L, 95L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 13494L, 51L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 13330L, 51L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 31209L, 63L)}));
    }

    private final Object m() {
        return new pq9("string:error_load_book_description", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 18262L, 167L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 15390L, 111L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 16152L, 139L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 23470L, 255L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 23794L, 119L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 15878L, 143L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 16450L, 143L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 25218L, 287L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 14708L, 123L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 15666L, 139L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 16926L, 147L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 16010L, 151L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 15704L, 107L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 15394L, 127L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 15722L, 143L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 21390L, 199L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 24662L, 231L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 15150L, 131L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 21450L, 159L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 13398L, 95L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 13234L, 95L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 31069L, 139L)}));
    }

    private final Object n() {
        return new pq9("string:create_account", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 12682L, 62L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 10754L, 54L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 11278L, 50L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 15838L, 94L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 19131L, 50L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 11058L, 46L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 11534L, 54L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 17074L, 74L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 10246L, 42L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 10970L, 50L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 11462L, 66L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 10834L, 50L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 11006L, 54L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 10862L, 46L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 10978L, 46L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 14682L, 78L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 16758L, 78L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 10454L, 50L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 14754L, 78L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 9314L, 42L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 9238L, 42L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 24810L, 54L)}));
    }

    private final Object o() {
        return new pq9("string:error_load_content", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 18641L, 74L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 15661L, 54L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 16491L, 70L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 24061L, 126L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 24069L, 58L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 16217L, 70L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 16793L, 70L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 25849L, 114L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 14999L, 62L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 15989L, 74L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 17293L, 82L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 16381L, 82L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 15971L, 58L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 15709L, 70L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 16077L, 82L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 21877L, 106L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 25213L, 118L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 15449L, 58L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 21865L, 98L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 13637L, 54L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 13473L, 54L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 31388L, 66L)}));
    }

    private final Object p() {
        return new pq9("string:error_load_content_description", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 18498L, 142L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 15554L, 106L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 16360L, 130L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 23838L, 222L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 23966L, 102L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 16090L, 126L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 16666L, 126L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 25610L, 238L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 14892L, 106L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 15878L, 110L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 17142L, 150L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 16238L, 142L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 15864L, 106L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 15590L, 118L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 15946L, 130L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 21682L, 194L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 25002L, 210L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 15334L, 114L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 21706L, 158L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 13546L, 90L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 13382L, 90L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 31273L, 114L)}));
    }

    private final Object q() {
        return new pq9("string:export_failed", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 19128L, 61L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 16048L, 53L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 16930L, 57L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 24756L, 85L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 25226L, 49L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 16648L, 57L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 17232L, 69L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 26592L, 89L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 15394L, 45L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 16408L, 57L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 17760L, 97L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 16880L, 77L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 16370L, 57L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 16116L, 65L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 16508L, 57L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 22516L, 101L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 25904L, 97L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 15828L, 61L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 22448L, 81L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 13960L, 49L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 13796L, 49L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 32701L, 57L)}));
    }

    private final Object r() {
        return new pq9("string:export_file", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 19190L, 43L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 16102L, 43L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 16988L, 43L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 24842L, 59L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 25276L, 35L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 16706L, 43L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 17302L, 47L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 26682L, 83L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 15440L, 35L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 16466L, 35L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 17858L, 63L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 16958L, 47L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 16428L, 43L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 16182L, 39L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 16566L, 43L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 22618L, 55L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 26002L, 59L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 15890L, 43L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 22530L, 63L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 14010L, 35L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 13846L, 35L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 32759L, 35L)}));
    }

    private final Object s() {
        return new pq9("string:export_format_file", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 25312L, 42L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 32795L, 54L)}));
    }

    private final Object t() {
        return new pq9("string:export_include_introduction", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 25355L, 63L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 32850L, 63L)}));
    }

    private final Object u() {
        return new pq9("string:export_include_table_of_content", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 25419L, 75L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 32914L, 71L)}));
    }

    @Override // defpackage.vt4
    public final Object invoke() {
        switch (this.a) {
            case 0:
                return new pq9("string:encoding", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 17181L, 36L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 14513L, 32L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 15225L, 28L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 22057L, 48L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 22914L, 28L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 14985L, 36L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 15597L, 28L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 23673L, 52L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 13869L, 28L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 14797L, 28L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 15833L, 36L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 15009L, 28L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 14817L, 28L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 14577L, 28L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 14861L, 36L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 20193L, 40L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 23197L, 60L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 14321L, 28L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 20257L, 40L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 12673L, 24L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 12525L, 24L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30013L, 28L)}));
            case 1:
                return new pq9("string:end_chapter", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 17218L, 47L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 14546L, 39L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 15254L, 35L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 22106L, 59L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 22943L, 39L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 15022L, 43L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 15626L, 39L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 23726L, 71L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 13898L, 31L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 14826L, 39L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 15870L, 47L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 15038L, 35L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 14846L, 39L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 14606L, 43L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 14898L, 43L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 20234L, 47L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 23258L, 35L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 14350L, 35L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 20298L, 55L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 12698L, 35L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 12550L, 35L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30042L, 39L)}));
            case 2:
                return new pq9("string:end_last_chapter", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 17266L, 72L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 14586L, 64L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 15290L, 64L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 22166L, 116L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 22983L, 56L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 15066L, 68L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 15666L, 60L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 23798L, 104L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 13930L, 52L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 14866L, 64L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 15918L, 60L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 15074L, 60L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 14886L, 56L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 14650L, 60L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 14942L, 64L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 20282L, 76L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 23294L, 104L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 14386L, 48L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 20354L, 96L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 12734L, 48L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 12586L, 48L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30082L, 56L)}));
            case 3:
                return new pq9("string:episode_count", b00.F0(new cr9[]{new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 15355L, 41L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 23040L, 41L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 13983L, 41L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 14943L, 49L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30139L, 37L)}));
            case 4:
                return new pq9("string:error_delete_account", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 23082L, 60L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30177L, 68L)}));
            case 5:
                return new pq9("string:copy", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 12661L, 20L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 10725L, 28L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 11253L, 24L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 15801L, 36L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 19110L, 20L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 11037L, 20L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 11513L, 20L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 17045L, 28L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 10225L, 20L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 10949L, 20L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 11437L, 24L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 10813L, 20L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 10977L, 28L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 10841L, 20L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 10957L, 20L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 14641L, 40L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 16721L, 36L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 10429L, 24L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 14717L, 36L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 9293L, 20L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 9217L, 20L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 24785L, 24L)}));
            case 6:
                return new pq9("string:error_edit_profile", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 17339L, 74L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 14651L, 66L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 15397L, 74L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 22283L, 106L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 23143L, 58L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 15135L, 74L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 15727L, 74L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 23903L, 102L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 14025L, 62L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 14931L, 74L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 15979L, 86L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 15135L, 82L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 14993L, 66L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 14711L, 78L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 15007L, 70L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 20359L, 94L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 23399L, 110L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 14435L, 58L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 20451L, 102L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 12783L, 50L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 12635L, 50L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30246L, 74L)}));
            case 7:
                return new pq9("string:create_topic_content_hint", fca.B(new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 25342L, 69L)));
            case 8:
                return new pq9("string:error_email_exist", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 17414L, 101L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 14718L, 53L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 15472L, 57L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 22390L, 69L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 23202L, 53L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 15210L, 53L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 15802L, 57L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 24006L, 101L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 14088L, 45L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 15006L, 53L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 16066L, 77L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 15218L, 77L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 15060L, 49L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 14790L, 53L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 15078L, 49L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 20454L, 69L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 23510L, 85L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 14494L, 53L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 20554L, 57L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 12834L, 53L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 12686L, 45L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30321L, 57L)}));
            case 9:
                return new pq9("string:error_email_not_valid", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 17516L, 97L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 14772L, 53L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 15530L, 57L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 22460L, 61L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 23256L, 49L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 15264L, 69L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 15860L, 49L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 24108L, 73L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 14134L, 53L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 15060L, 53L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 16144L, 77L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 15296L, 81L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 15110L, 57L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 14844L, 57L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 15128L, 49L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 20524L, 81L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 23596L, 89L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 14548L, 53L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 20612L, 61L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 12888L, 53L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 12732L, 45L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30379L, 61L)}));
            case 10:
                return new pq9("string:error_empty_content", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 17770L, 63L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 14970L, 47L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 15728L, 43L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 22746L, 87L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 23426L, 43L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 15458L, 51L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 16042L, 47L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 24422L, 91L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 14308L, 51L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 15246L, 51L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 16390L, 75L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 15526L, 63L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 15292L, 43L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 15022L, 47L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 15294L, 47L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 20810L, 67L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 23930L, 75L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 14734L, 47L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 20858L, 67L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 13050L, 47L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 12882L, 47L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30581L, 59L)}));
            case 11:
                return a();
            case 12:
                return b();
            case 13:
                return e();
            case 14:
                return f();
            case 15:
                return g();
            case 16:
                return m();
            case 17:
                return n();
            case 18:
                return new pq9("string:create_topic_edit_title", fca.B(new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 25412L, 55L)));
            case 19:
                return o();
            case 20:
                return new pq9("string:export_error_html_failed", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 25058L, 56L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 32509L, 64L)}));
            case 21:
                return p();
            case 22:
                return new pq9("string:export_error_save_file", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 25115L, 54L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 32574L, 62L)}));
            case 23:
                return new pq9("string:export_error_txt_failed", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 25170L, 55L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 32637L, 63L)}));
            case 24:
                return q();
            case 25:
                return r();
            case 26:
                return s();
            case 27:
                return t();
            case 28:
                return u();
            default:
                return new pq9("string:export_merge_into_single_file", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 25495L, 69L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 32986L, 65L)}));
        }
    }
}
