package defpackage;
/* compiled from: r8-map-id-f559a6c9210f67746bd9ce87931ee85b676f3bda66e04dc5e85cb7e8eec71de1 */
/* renamed from: n3b  reason: default package */
/* loaded from: classes3.dex */
public final /* synthetic */ class n3b implements vt4 {
    public final /* synthetic */ int a;

    public /* synthetic */ n3b(int i) {
        this.a = i;
    }

    private final Object a() {
        return new pq9("string:translate_qt_download", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 52411L, 89L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 42863L, 69L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 44867L, 77L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 64855L, 101L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 57099L, 65L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 44275L, 77L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 45903L, 85L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 68667L, 133L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 41231L, 57L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 43323L, 69L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 45763L, 73L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 43975L, 65L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 43179L, 73L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 43243L, 65L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 43819L, 65L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 59655L, 101L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 68019L, 133L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 42363L, 69L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 59599L, 121L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 36743L, 53L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 36515L, 53L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 70387L, 73L)}));
    }

    private final Object b() {
        return new pq9("string:translate_qt_export_failed", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 52501L, 86L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 42933L, 74L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 44945L, 94L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 64957L, 106L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 57165L, 74L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 44353L, 82L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 45989L, 98L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 68801L, 122L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 41289L, 66L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 43393L, 86L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 45837L, 110L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 44041L, 98L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 43253L, 82L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 43309L, 90L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 43885L, 82L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 59757L, 126L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 68153L, 138L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 42433L, 86L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 59721L, 110L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 36797L, 70L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 36569L, 70L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 70461L, 86L)}));
    }

    private final Object e() {
        return new pq9("string:translate_qt_export_success", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 52588L, 99L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 43008L, 87L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 45040L, 91L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 65064L, 143L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 57240L, 83L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 44436L, 87L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 46088L, 91L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 68924L, 119L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 41356L, 71L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 43480L, 87L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 45948L, 111L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 44140L, 103L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 43336L, 91L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 43400L, 91L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 43968L, 87L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 59884L, 119L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 68292L, 127L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 42520L, 99L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 59832L, 115L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 36868L, 71L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 36640L, 71L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 70548L, 87L)}));
    }

    /* JADX WARN: Type inference failed for: r1v30, types: [java.lang.Object, al6, y28] */
    @Override // defpackage.vt4
    public final Object invoke() {
        switch (this.a) {
            case 0:
                return new pq9("string:translate_qt_dic_discard_message", fca.B(new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 69343L, 116L)));
            case 1:
                return new pq9("string:translate_qt_dic_discard_title", fca.B(new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 69460L, 62L)));
            case 2:
                return new pq9("string:translate_qt_dic_import_confirm", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 51514L, 59L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 42170L, 55L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 44130L, 55L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 63766L, 63L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 56390L, 47L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 43542L, 51L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 45146L, 51L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 67554L, 55L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 40586L, 47L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 42618L, 51L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 45014L, 59L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 43266L, 55L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 42450L, 55L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 42574L, 51L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 43106L, 51L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 58710L, 55L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 66950L, 63L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 41674L, 55L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 58702L, 55L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 36154L, 47L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 35946L, 47L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 69523L, 47L)}));
            case 3:
                return new pq9("string:translate_qt_dic_import_title", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 51574L, 77L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 42226L, 65L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 44186L, 69L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 63830L, 81L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 56438L, 61L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 43594L, 65L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 45198L, 69L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 67610L, 101L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 40634L, 53L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 42670L, 61L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 45074L, 69L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 43322L, 65L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 42506L, 69L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 42626L, 61L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 43158L, 65L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 58766L, 73L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 67014L, 97L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 41730L, 65L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 58758L, 77L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 36202L, 53L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 35994L, 53L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 69571L, 65L)}));
            case 4:
                return new pq9("string:translate_qt_dic_mode_merge", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 51837L, 63L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 42425L, 59L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 44389L, 71L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 64129L, 83L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 56637L, 59L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 43809L, 63L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 45409L, 71L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 67965L, 99L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 40809L, 55L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 42865L, 59L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 45289L, 59L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 43529L, 55L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 42697L, 67L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 42809L, 55L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 43361L, 63L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 59029L, 83L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 67305L, 83L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 41925L, 67L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 59013L, 79L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 36361L, 51L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 36149L, 51L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 69754L, 59L)}));
            case 5:
                return new pq9("string:stat_book_chapter_count", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 52577L, 51L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 65041L, 51L)}));
            case 6:
                return new pq9("string:translate_qt_dic_mode_merge_desc", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 51652L, 184L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 42292L, 132L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 44256L, 132L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 63912L, 216L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 56500L, 136L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 43660L, 148L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 45268L, 140L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 67712L, 252L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 40688L, 120L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 42732L, 132L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 45144L, 144L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 43388L, 140L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 42576L, 120L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 42688L, 120L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 43224L, 136L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 58840L, 188L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 67112L, 192L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 41796L, 128L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 58836L, 176L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 36256L, 104L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 36048L, 100L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 69637L, 116L)}));
            case 7:
                return new pq9("string:stat_read_time", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 52996L, 38L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 65508L, 46L)}));
            case 8:
                return new pq9("string:translate_qt_dic_mode_missing", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 52100L, 105L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 42616L, 81L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 44600L, 85L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 64436L, 133L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 56848L, 69L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 44012L, 81L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 45624L, 93L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 68308L, 117L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 41000L, 69L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 43056L, 77L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 45500L, 65L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 43716L, 73L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 42912L, 77L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 43008L, 69L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 43560L, 85L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 59316L, 113L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 67596L, 109L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 42124L, 69L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 59276L, 89L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 36524L, 69L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 36304L, 61L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 69949L, 69L)}));
            case 9:
                return new pq9("string:translate_qt_dic_mode_missing_desc", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 51901L, 198L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 42485L, 130L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 44461L, 138L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 64213L, 222L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 56697L, 150L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 43873L, 138L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 45481L, 142L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 68065L, 242L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 40865L, 134L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 42925L, 130L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 45349L, 150L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 43585L, 130L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 42765L, 146L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 42865L, 142L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 43425L, 134L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 59113L, 202L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 67389L, 206L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 41993L, 130L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 59093L, 182L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 36413L, 110L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 36201L, 102L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 69814L, 134L)}));
            case 10:
                return new pq9("string:translate_qt_dic_mode_replace", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 52341L, 69L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 42805L, 57L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 44809L, 57L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 64769L, 85L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 57045L, 53L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 44217L, 57L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 45845L, 57L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 68597L, 69L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 41177L, 53L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 43261L, 61L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 45697L, 65L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 43913L, 61L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 43121L, 57L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 43181L, 61L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 43761L, 57L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 59585L, 69L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 67929L, 89L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 42297L, 65L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 59529L, 69L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 36689L, 53L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 36461L, 53L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 70150L, 65L)}));
            case 11:
                return new pq9("string:translate_qt_dic_mode_replace_desc", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 52206L, 134L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 42698L, 106L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 44686L, 122L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 64570L, 198L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 56918L, 126L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 44094L, 122L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 45718L, 126L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 68426L, 170L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 41070L, 106L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 43134L, 126L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 45566L, 130L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 43790L, 122L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 42990L, 130L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 43078L, 102L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 43646L, 114L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 59430L, 154L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 67706L, 222L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 42194L, 102L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 59366L, 162L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 36594L, 94L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 36366L, 94L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 70019L, 130L)}));
            case 12:
                return new pq9("string:translate_qt_dic_save_failed", fca.B(new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 70216L, 84L)));
            case 13:
                return new pq9("string:translate_qt_dic_save_success", fca.B(new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 70301L, 85L)));
            case 14:
                return a();
            case 15:
                return b();
            case 16:
                return e();
            case 17:
                return new pq9("string:stat_book_count", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 52629L, 31L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 65093L, 43L)}));
            case 18:
                return new pq9("string:stat_recent_sessions", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 53035L, 48L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 65555L, 52L)}));
            case 19:
                return ks3.a;
            case 20:
                return "";
            case 21:
                return new StringBuilder(1024);
            case 22:
                return new gl5();
            case 23:
                ?? obj = new Object();
                obj.d = "";
                return new n38(obj, cm9.a(y28.class));
            case 24:
                return new rg3(nae.e);
            case 25:
                return bue.a(100.0f);
            case 26:
                return new mea(4.0f, zl1.b(0.05f, zl1.b), 26);
            case 27:
                c4b c4bVar = c4b.a;
                return new b45(c4bVar, c4bVar, 1);
            case 28:
                c4b c4bVar2 = c4b.a;
                return new b45(c4bVar2, c4bVar2, 1);
            default:
                return new sz(c4b.a, 0);
        }
    }
}
