package defpackage;
/* compiled from: r8-map-id-f559a6c9210f67746bd9ce87931ee85b676f3bda66e04dc5e85cb7e8eec71de1 */
/* renamed from: osc  reason: default package */
/* loaded from: classes.dex */
public abstract class osc {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final dq4 D;
    public static final uw4 E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final dq4 I;
    public static final uw4 J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final dq4 N;
    public static final uw4 O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final dq4 S;
    public static final uw4 T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final dq4 X;
    public static final uw4 Y;
    public static final long Z;
    public static final uw4 a;
    public static final long a0;
    public static final long b;
    public static final long b0;
    public static final long c;
    public static final dq4 c0;
    public static final long d;
    public static final uw4 d0;
    public static final dq4 e;
    public static final long e0;
    public static final uw4 f;
    public static final long f0;
    public static final long g;
    public static final long g0;
    public static final long h;
    public static final dq4 h0;
    public static final long i;
    public static final uw4 i0;
    public static final dq4 j;
    public static final long j0;
    public static final uw4 k;
    public static final long k0;
    public static final long l;
    public static final long l0;
    public static final long m;
    public static final dq4 m0;
    public static final long n;
    public static final uw4 n0;
    public static final dq4 o;
    public static final long o0;
    public static final uw4 p;
    public static final long p0;
    public static final long q;
    public static final long q0;
    public static final long r;
    public static final dq4 r0;
    public static final long s;
    public static final uw4 s0;
    public static final dq4 t;
    public static final long t0;
    public static final uw4 u;
    public static final long u0;
    public static final long v;
    public static final long v0;
    public static final long w;
    public static final dq4 w0;
    public static final long x;
    public static final dq4 y;
    public static final uw4 z;

    static {
        dq4 dq4Var = dtc.a;
        uw4 uw4Var = eo4.b;
        a = uw4Var;
        b = zr1.p(24.0d);
        c = zr1.q(16);
        d = zr1.p(0.5d);
        dq4 dq4Var2 = dtc.b;
        e = dq4Var2;
        f = uw4Var;
        g = zr1.p(20.0d);
        h = zr1.q(14);
        i = zr1.p(0.2d);
        j = dq4Var2;
        k = uw4Var;
        l = zr1.p(16.0d);
        m = zr1.q(12);
        n = zr1.p(0.4d);
        o = dq4Var2;
        p = uw4Var;
        q = zr1.p(64.0d);
        r = zr1.q(57);
        long p2 = zr1.p(0.2d);
        zr1.k(p2);
        s = zr1.x(-e4c.c(p2), p2 & 1095216660480L);
        t = dq4Var2;
        u = uw4Var;
        v = zr1.p(52.0d);
        w = zr1.q(45);
        x = zr1.p(0.0d);
        y = dq4Var2;
        z = uw4Var;
        A = zr1.p(44.0d);
        B = zr1.q(36);
        C = zr1.p(0.0d);
        D = dq4Var2;
        E = uw4Var;
        F = zr1.p(40.0d);
        G = zr1.q(32);
        H = zr1.p(0.0d);
        I = dq4Var2;
        J = uw4Var;
        K = zr1.p(36.0d);
        L = zr1.q(28);
        M = zr1.p(0.0d);
        N = dq4Var2;
        O = uw4Var;
        P = zr1.p(32.0d);
        Q = zr1.q(24);
        R = zr1.p(0.0d);
        S = dq4Var2;
        T = uw4Var;
        U = zr1.p(20.0d);
        V = zr1.q(14);
        W = zr1.p(0.1d);
        dq4 dq4Var3 = dtc.a;
        X = dq4Var3;
        Y = uw4Var;
        Z = zr1.p(16.0d);
        a0 = zr1.q(12);
        b0 = zr1.p(0.5d);
        c0 = dq4Var3;
        d0 = uw4Var;
        e0 = zr1.p(16.0d);
        f0 = zr1.q(11);
        g0 = zr1.p(0.5d);
        h0 = dq4Var3;
        i0 = uw4Var;
        j0 = zr1.p(28.0d);
        k0 = zr1.q(22);
        l0 = zr1.p(0.0d);
        m0 = dq4Var2;
        n0 = uw4Var;
        o0 = zr1.p(24.0d);
        p0 = zr1.q(16);
        q0 = zr1.p(0.2d);
        r0 = dq4Var3;
        s0 = uw4Var;
        t0 = zr1.p(20.0d);
        u0 = zr1.q(14);
        v0 = zr1.p(0.1d);
        w0 = dq4Var3;
        zr1.p(24.0d);
        zr1.q(16);
        zr1.p(0.15d);
        zr1.p(20.0d);
        zr1.q(14);
        zr1.p(0.25d);
        zr1.p(16.0d);
        zr1.q(12);
        zr1.p(0.4d);
        zr1.p(64.0d);
        zr1.q(57);
        zr1.q(0);
        zr1.p(52.0d);
        zr1.q(45);
        zr1.q(0);
        zr1.p(44.0d);
        zr1.q(36);
        zr1.q(0);
        zr1.p(40.0d);
        zr1.q(32);
        zr1.q(0);
        zr1.p(36.0d);
        zr1.q(28);
        zr1.q(0);
        zr1.p(32.0d);
        zr1.q(24);
        zr1.q(0);
        zr1.p(20.0d);
        zr1.q(14);
        zr1.p(0.1d);
        zr1.p(16.0d);
        zr1.q(12);
        zr1.p(0.5d);
        zr1.p(16.0d);
        zr1.q(11);
        zr1.p(0.5d);
        zr1.p(28.0d);
        zr1.q(22);
        zr1.q(0);
        zr1.p(24.0d);
        zr1.q(16);
        zr1.p(0.15d);
        zr1.p(20.0d);
        zr1.q(14);
        zr1.p(0.1d);
    }
}
