package defpackage;
/* compiled from: r8-map-id-f559a6c9210f67746bd9ce87931ee85b676f3bda66e04dc5e85cb7e8eec71de1 */
/* renamed from: y1b  reason: default package */
/* loaded from: classes3.dex */
public final /* synthetic */ class y1b implements vt4 {
    public final /* synthetic */ int a;

    private final Object a() {
        return new pq9("string:video_setting_subtitle_padding", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 59148L, 74L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 48500L, 58L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 50796L, 58L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 73296L, 74L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 64528L, 58L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 50080L, 58L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 51764L, 62L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 77580L, 78L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 46444L, 54L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 49000L, 62L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 51552L, 54L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 49628L, 58L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 48664L, 58L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 48988L, 58L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 49656L, 58L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 67404L, 74L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 77144L, 82L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 47868L, 54L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 67272L, 74L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 41524L, 54L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 41260L, 54L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 78972L, 66L)}));
    }

    private final Object b() {
        return new pq9("string:video_setting_subtitle_text_color", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 59223L, 61L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 48559L, 57L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 50855L, 53L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 73371L, 77L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 64587L, 57L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 50139L, 61L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 51827L, 65L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 77659L, 85L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 46499L, 57L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 49063L, 57L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 51607L, 53L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 49687L, 57L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 48723L, 57L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 49047L, 57L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 49715L, 57L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 67479L, 69L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 77227L, 77L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 47923L, 57L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 67347L, 73L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 41579L, 57L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 41315L, 57L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 79039L, 57L)}));
    }

    private final Object e() {
        return new pq9("string:video_setting_mute", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 63521L, 34L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 77873L, 46L)}));
    }

    private final Object f() {
        return new pq9("string:week", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 59285L, 28L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 48617L, 20L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 50909L, 20L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 73449L, 36L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 64866L, 20L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 50201L, 20L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 51893L, 24L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 77745L, 36L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 46557L, 20L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 49121L, 24L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 51661L, 16L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 49745L, 16L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 48781L, 20L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 49105L, 24L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 49773L, 20L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 67549L, 28L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 77305L, 40L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 47981L, 20L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 67421L, 32L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 41637L, 16L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 41373L, 16L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 79522L, 20L)}));
    }

    private final Object g() {
        return new pq9("string:welcome_back", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 59314L, 56L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 48638L, 40L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 50930L, 48L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 73486L, 64L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 64887L, 36L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 50222L, 48L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 51918L, 36L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 77782L, 76L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 46578L, 52L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 49146L, 36L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 51678L, 48L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 49762L, 68L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 48802L, 36L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 49130L, 40L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 49794L, 44L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 67578L, 56L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 77346L, 84L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 48002L, 48L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 67454L, 56L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 41654L, 36L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 41390L, 36L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 79543L, 52L)}));
    }

    @Override // defpackage.vt4
    public final Object invoke() {
        switch (this.a) {
            case 0:
                return new pq9("string:translate_save_book", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 54202L, 51L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 44434L, 43L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 46590L, 43L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 67154L, 63L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 58606L, 39L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 45890L, 47L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 47590L, 47L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 71026L, 59L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 42642L, 43L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 44894L, 51L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 47342L, 43L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 45546L, 43L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 44750L, 39L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 44838L, 43L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 45446L, 47L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 61774L, 51L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 70762L, 59L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 43902L, 39L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 61718L, 47L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 38102L, 35L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 37854L, 39L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 72022L, 47L)}));
            case 1:
                return new pq9("string:video_setting_auto_brightness", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 62842L, 57L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 77074L, 69L)}));
            case 2:
                return new pq9("string:video_setting_auto_next_episode", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 62900L, 63L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 77144L, 75L)}));
            case 3:
                return new pq9("string:video_setting_auto_play", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 62964L, 43L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 77220L, 55L)}));
            case 4:
                return new pq9("string:video_setting_auto_resume_last_position", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 63008L, 87L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 77276L, 115L)}));
            case 5:
                return new pq9("string:video_setting_brightness", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 63164L, 48L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 77468L, 48L)}));
            case 6:
                return new pq9("string:video_setting_brightness_volume", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 63096L, 67L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 77392L, 75L)}));
            case 7:
                return new pq9("string:video_setting_continue_play_in_pip", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 63213L, 74L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 77517L, 82L)}));
            case 8:
                return new pq9("string:video_setting_dark_mode", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 63288L, 43L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 77600L, 55L)}));
            case 9:
                return new pq9("string:video_setting_default_volume", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 63332L, 56L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 77656L, 72L)}));
            case 10:
                return new pq9("string:translate_qt_other_dictionary_title", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 53482L, 83L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 43810L, 71L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 45894L, 83L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 66294L, 95L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 58006L, 71L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 45246L, 83L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 46934L, 79L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 70066L, 103L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 42058L, 71L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 44290L, 75L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 46774L, 59L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 44966L, 63L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 44130L, 71L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 44206L, 75L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 44794L, 83L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 60966L, 91L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 69594L, 107L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 43326L, 67L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 60866L, 103L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 37558L, 59L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 37306L, 59L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 71366L, 67L)}));
            case 11:
                return new pq9("string:translate_save_extension", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 54254L, 60L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 44478L, 52L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 46634L, 48L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 67218L, 64L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 58646L, 44L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 45938L, 48L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 47638L, 48L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 71086L, 56L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 42686L, 48L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 44946L, 48L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 47386L, 52L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 45590L, 52L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 44790L, 48L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 44882L, 44L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 45494L, 48L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 61826L, 64L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 70822L, 60L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 43942L, 44L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 61766L, 60L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 38138L, 44L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 37894L, 44L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 72070L, 48L)}));
            case 12:
                return new pq9("string:video_setting_display", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 63389L, 41L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 77729L, 45L)}));
            case 13:
                return new pq9("string:video_setting_subtitle_font_medium", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 58967L, 58L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 48319L, 54L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 50631L, 50L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 73075L, 58L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 64327L, 50L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 49911L, 50L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 51607L, 50L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 77355L, 62L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 46279L, 50L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 48827L, 50L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 51375L, 62L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 49463L, 50L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 48495L, 50L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 48811L, 54L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 49487L, 50L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 67199L, 62L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 76923L, 58L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 47695L, 50L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 67059L, 66L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 41363L, 50L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 41099L, 50L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 78755L, 50L)}));
            case 14:
                return new pq9("string:video_setting_lock_orientation_fullscreen", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 63431L, 89L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 77775L, 97L)}));
            case 15:
                return new pq9("string:video_setting_subtitle_font_normal", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 59026L, 54L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 48374L, 58L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 50682L, 50L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 73134L, 66L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 64378L, 50L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 49962L, 50L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 51658L, 50L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 77418L, 70L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 46330L, 50L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 48878L, 54L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 51438L, 50L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 49514L, 50L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 48546L, 54L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 48866L, 54L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 49538L, 50L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 67262L, 62L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 76982L, 58L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 47746L, 50L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 67126L, 66L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 41414L, 50L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 41150L, 50L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 78806L, 54L)}));
            case 16:
                return new pq9("string:video_setting_subtitle_font_weight", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 59081L, 66L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 48433L, 66L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 50733L, 62L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 73201L, 94L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 64429L, 58L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 50013L, 66L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 51709L, 54L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 77489L, 90L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 46381L, 62L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 48933L, 66L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 51489L, 62L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 49565L, 62L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 48601L, 62L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 48921L, 66L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 49589L, 66L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 67325L, 78L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 77041L, 102L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 47797L, 70L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 67193L, 78L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 41465L, 58L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 41201L, 58L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 78861L, 66L)}));
            case 17:
                return new pq9("string:video_setting_subtitle_none", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 64488L, 39L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 78928L, 43L)}));
            case 18:
                return a();
            case 19:
                return b();
            case 20:
                return new pq9("string:video_setting_subtitle_text_size", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 64645L, 64L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 79097L, 72L)}));
            case 21:
                return new pq9("string:video_setting_subtitle_track", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 64710L, 48L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 79170L, 52L)}));
            case 22:
                return new pq9("string:video_skip_segment", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 64802L, 34L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 79270L, 38L)}));
            case 23:
                return new pq9("string:video_setting_seconds", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 63877L, 37L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 78301L, 45L)}));
            case 24:
                return new pq9("string:view_all", b00.F0(new cr9[]{new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 64837L, 28L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 79309L, 36L)}));
            case 25:
                return new pq9("string:vlc_missing_message", fca.B(new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 79346L, 175L)));
            case 26:
                return e();
            case 27:
                return f();
            case 28:
                return g();
            default:
                return new pq9("string:word_count", b00.F0(new cr9[]{new cr9(a82.r("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 59371L, 38L), new cr9(a82.r("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 48679L, 30L), new cr9(a82.r("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 50979L, 38L), new cr9(a82.r("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 73551L, 42L), new cr9(a82.r("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 64924L, 34L), new cr9(a82.r("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 50271L, 38L), new cr9(a82.r("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 51955L, 30L), new cr9(a82.r("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 77859L, 42L), new cr9(a82.r("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 46631L, 30L), new cr9(a82.r("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 49183L, 34L), new cr9(a82.r("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 51727L, 34L), new cr9(a82.r("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 49831L, 38L), new cr9(a82.r("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 48839L, 34L), new cr9(a82.r("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 49171L, 34L), new cr9(a82.r("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 49839L, 38L), new cr9(a82.r("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 67635L, 38L), new cr9(a82.r("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 77431L, 34L), new cr9(a82.r("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 48051L, 34L), new cr9(a82.r("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 67511L, 38L), new cr9(b00.F0(new of9[]{new ub6("zh"), new km9("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 41691L, 34L), new cr9(a82.r("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 41427L, 34L), new cr9(rs3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 79596L, 30L)}));
        }
    }
}
