package defpackage;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import org.mozilla.javascript.Context;
import org.mozilla.javascript.Parser;
/* compiled from: r8-map-id-f559a6c9210f67746bd9ce87931ee85b676f3bda66e04dc5e85cb7e8eec71de1 */
/* renamed from: yme  reason: default package */
/* loaded from: classes.dex */
public abstract class yme {
    public static final wme A;
    public static final wme A0;
    public static final wme B;
    public static final wme B0;
    public static final wme C;
    public static final wme C0;
    public static final wme D;
    public static final wme D0;
    public static final wme E;
    public static final wme E0;
    public static final wme F;
    public static final wme F0;
    public static final wme G;
    public static final wme G0;
    public static final wme H;
    public static final wme H0;
    public static final wme I;
    public static final wme I0;
    public static final wme J;
    public static final wme J0;
    public static final wme K;
    public static final wme K0;
    public static final wme L;
    public static final wme L0;
    public static final wme M;
    public static final wme M0;
    public static final wme N;
    public static final wme N0;
    public static final wme O;
    public static final wme O0;
    public static final wme P;
    public static final wme P0;
    public static final wme Q;
    public static final wme Q0;
    public static final wme R;
    public static final wme R0;
    public static final wme S;
    public static final wme S0;
    public static final wme T;
    public static final wme T0;
    public static final wme U;
    public static final wme U0;
    public static final wme V;
    public static final wme V0;
    public static final wme W;
    public static final wme W0;
    public static final wme X;
    public static final wme X0;
    public static final wme Y;
    public static final wme Y0;
    public static final wme Z;
    public static final wme Z0;
    public static final List a = Collections.synchronizedList(new ArrayList());
    public static final wme a0;
    public static final wme a1;
    public static final wme b;
    public static final wme b0;
    public static final wme b1;
    public static final wme c;
    public static final wme c0;
    public static final wme c1;
    public static final wme d;
    public static final wme d0;
    public static final wme d1;
    public static final wme e;
    public static final wme e0;
    public static final wme e1;
    public static final wme f;
    public static final wme f0;
    public static final wme f1;
    public static final wme g;
    public static final wme g0;
    public static final wme g1;
    public static final wme h;
    public static final wme h0;
    public static final wme h1;
    public static final wme i;
    public static final wme i0;
    public static final wme i1;
    public static final wme j;
    public static final wme j0;
    public static final wme j1;
    public static final wme k;
    public static final wme k0;
    public static final wme l;
    public static final wme l0;
    public static final wme m;
    public static final wme m0;
    public static final wme n;
    public static final wme n0;
    public static final wme o;
    public static final wme o0;
    public static final wme p;
    public static final wme p0;
    public static final wme q;
    public static final wme q0;
    public static final wme r;
    public static final wme r0;
    public static final wme s;
    public static final wme s0;
    public static final wme t;
    public static final wme t0;
    public static final wme u;
    public static final wme u0;
    public static final wme v;
    public static final wme v0;
    public static final wme w;
    public static final wme w0;
    public static final wme x;
    public static final wme x0;
    public static final wme y;
    public static final wme y0;
    public static final wme z;
    public static final wme z0;

    static {
        Collections.synchronizedSet(new HashSet());
        b = a("measurement.ad_id_cache_time", 10000L, d38.H, false);
        c = a("measurement.app_uninstalled_additional_ad_id_cache_time", 3600000L, v28.c, false);
        d = a("measurement.monitoring.sample_period_millis", 86400000L, pq8.d, false);
        e = a("measurement.config.cache_time", 86400000L, iv8.e, false);
        f = a("measurement.config.url_scheme", "https", u28.f, false);
        g = a("measurement.config.url_authority", "app-measurement.com", v28.C, false);
        h = a("measurement.upload.max_bundles", 100, v28.D, false);
        Integer valueOf = Integer.valueOf((int) Parser.ARGC_LIMIT);
        i = a("measurement.upload.max_batch_size", valueOf, d38.E, false);
        j = a("measurement.upload.max_bundle_size", valueOf, d38.F, false);
        k = a("measurement.upload.max_events_per_bundle", 1000, mp8.H, false);
        l = a("measurement.upload.max_events_per_day", 100000, v28.H, false);
        m = a("measurement.upload.max_error_events_per_day", 1000, pq8.c, false);
        n = a("measurement.upload.max_public_events_per_day", 50000, iv8.d, false);
        o = a("measurement.upload.max_conversions_per_day", 10000, tw8.d, false);
        p = a("measurement.upload.max_realtime_events_per_day", 10, u28.c, false);
        q = a("measurement.store.max_stored_events_per_app", 100000, v28.d, false);
        r = a("measurement.upload.url", "https://app-measurement.com/a", h88.d, false);
        s = a("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d", jf8.d, false);
        t = a("measurement.sgtm.service_upload_apps_list", "", bl8.d, false);
        u = a("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504", fn8.d, false);
        v = a("measurement.sgtm.upload.retry_interval", 600000L, mp8.d, false);
        w = a("measurement.sgtm.upload.retry_max_wait", 21600000L, tw8.e, false);
        x = a("measurement.sgtm.batch.retry_interval", 1800000L, u28.d, false);
        y = a("measurement.sgtm.batch.retry_max_wait", 21600000L, v28.e, false);
        z = a("measurement.sgtm.batch.retry_max_count", 10, d38.d, false);
        A = a("measurement.sgtm.upload.max_queued_batches", 5000, h88.e, false);
        B = a("measurement.sgtm.upload.batches_retrieval_limit", 5, jf8.e, false);
        C = a("measurement.sgtm.upload.min_delay_after_startup", 5000L, bl8.e, false);
        D = a("measurement.sgtm.upload.min_delay_after_broadcast", 1000L, fn8.e, false);
        E = a("measurement.sgtm.upload.min_delay_after_background", 600000L, mp8.e, false);
        F = a("measurement.sgtm.batch.long_queuing_threshold", 14400000L, pq8.e, false);
        G = a("measurement.upload.backoff_period", 43200000L, tw8.f, false);
        a("measurement.upload.window_interval", 3600000L, u28.e, false);
        H = a("measurement.upload.interval", 3600000L, v28.f, false);
        I = a("measurement.upload.realtime_upload_interval", 10000L, d38.e, false);
        J = a("measurement.upload.debug_upload_interval", 1000L, h88.f, false);
        K = a("measurement.upload.minimum_delay", 500L, jf8.f, false);
        L = a("measurement.alarm_manager.minimum_interval", 60000L, bl8.f, false);
        M = a("measurement.upload.stale_data_deletion_interval", 86400000L, fn8.f, false);
        N = a("measurement.upload.refresh_blacklisted_config_interval", 604800000L, mp8.f, false);
        O = a("measurement.upload.initial_upload_delay_time", 15000L, iv8.f, false);
        P = a("measurement.upload.retry_time", 1800000L, d38.f, false);
        Q = a("measurement.upload.retry_count", 6, h88.C, false);
        R = a("measurement.upload.max_queue_time", 518400000L, jf8.C, false);
        S = a("measurement.upload.google_signal_max_queue_time", 300000L, bl8.C, false);
        T = a("measurement.lifetimevalue.max_currency_tracked", 4, fn8.C, false);
        U = a("measurement.audience.filter_result_max_count", Integer.valueOf((int) Context.VERSION_ES6), mp8.C, false);
        V = a("measurement.upload.max_public_user_properties", 100, null, false);
        W = a("measurement.upload.max_event_name_cardinality", 2000, null, false);
        X = a("measurement.upload.max_public_event_params", 100, null, false);
        Y = a("measurement.service_client.idle_disconnect_millis", 5000L, pq8.f, false);
        Z = a("measurement.service_client.reconnect_millis", 1000L, iv8.C, false);
        Boolean bool = Boolean.FALSE;
        a0 = a("measurement.test.test_boolean_flag", bool, tw8.C, false);
        b0 = a("measurement.test.test_string_flag", "---", u28.C, false);
        c0 = a("measurement.test.test_long_flag", -1L, d38.C, false);
        a("measurement.test.test_cached_long_flag", -1L, h88.D, true);
        d0 = a("measurement.test.test_int_flag", -2, jf8.D, false);
        e0 = a("measurement.test.test_double_flag", Double.valueOf(-3.0d), bl8.D, false);
        a("measurement.experiment.max_ids", 50, fn8.D, false);
        f0 = a("measurement.upload.max_item_scoped_custom_parameters", 27, mp8.D, false);
        g0 = a("measurement.upload.max_event_parameter_value_length", 500, pq8.C, true);
        h0 = a("measurement.max_bundles_per_iteration", 100, iv8.D, false);
        i0 = a("measurement.sdk.attribution.cache.ttl", 604800000L, tw8.D, false);
        j0 = a("measurement.redaction.app_instance_id.ttl", 7200000L, u28.D, false);
        k0 = a("measurement.rb.attribution.client.min_ad_services_version", 7, d38.D, false);
        l0 = a("measurement.dma_consent.max_daily_dcu_realtime_events", 1, h88.E, false);
        m0 = a("measurement.rb.attribution.uri_scheme", "https", bl8.E, false);
        n0 = a("measurement.rb.attribution.uri_authority", "google-analytics.com", fn8.E, false);
        o0 = a("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion", mp8.E, false);
        p0 = a("measurement.session.engagement_interval", 3600000L, pq8.D, false);
        q0 = a("measurement.rb.attribution.app_allowlist", "", iv8.E, false);
        r0 = a("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot", tw8.E, false);
        s0 = a("measurement.rb.attribution.event_params", "value|currency", u28.E, false);
        t0 = a("measurement.rb.attribution.query_parameters_to_remove", "", v28.E, false);
        u0 = a("measurement.rb.attribution.max_queue_time", 864000000L, h88.F, false);
        v0 = a("measurement.rb.attribution.max_retry_delay_seconds", 16, jf8.E, false);
        w0 = a("measurement.rb.attribution.client.min_time_after_boot_seconds", 90, bl8.F, false);
        a("measurement.rb.attribution.max_trigger_uris_queried_at_once", 0, fn8.F, false);
        x0 = a("measurement.rb.max_trigger_registrations_per_day", 1000, mp8.F, false);
        Boolean bool2 = Boolean.TRUE;
        y0 = a("measurement.config.bundle_for_all_apps_on_backgrounded", bool2, pq8.E, false);
        z0 = a("measurement.config.notify_trigger_uris_on_backgrounded", bool2, iv8.F, false);
        A0 = a("measurement.rb.attribution.notify_app_delay_millis", 3000, tw8.F, false);
        a("measurement.config.default_flag_values", bool2, u28.F, false);
        B0 = a("measurement.upload.diagnostic_upload_interval", 3600000L, v28.F, false);
        C0 = a("measurement.quality.checksum", bool, null, false);
        D0 = a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, h88.G, false);
        E0 = a("measurement.audience.refresh_event_count_filters_timestamp", bool, jf8.F, false);
        F0 = a("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, bl8.G, true);
        G0 = a("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, fn8.G, false);
        H0 = a("measurement.integration.disable_firebase_instance_id", bool, mp8.G, false);
        I0 = a("measurement.collection.service.update_with_analytics_fix", bool, pq8.F, false);
        J0 = a("measurement.service.storage_consent_support_version", 203600, u28.G, false);
        K0 = a("measurement.service.store_null_safelist", bool2, d38.G, false);
        L0 = a("measurement.service.store_safelist", bool2, h88.H, false);
        M0 = a("measurement.session_stitching_token_enabled", bool, bl8.H, false);
        N0 = a("measurement.sgtm.client.upload_on_backgrounded.dev", bool, pq8.G, true);
        O0 = a("measurement.rb.attribution.service", bool2, tw8.G, true);
        P0 = a("measurement.rb.attribution.client2", bool2, u28.H, true);
        Q0 = a("measurement.rb.attribution.uuid_generation", bool2, v28.G, false);
        R0 = a("measurement.rb.attribution.enable_trigger_redaction", bool2, h88.I, false);
        S0 = a("measurement.client.sessions.enable_fix_background_engagement", bool2, mp8.J, false);
        a("measurement.rb.attribution.service.enable_max_trigger_uris_queried_at_once", bool2, jf8.G, false);
        a("measurement.remove_conflicting_first_party_apis.dev", bool, bl8.I, false);
        T0 = a("measurement.rb.attribution.service.trigger_uris_high_priority", bool2, mp8.I, false);
        U0 = a("measurement.experiment.enable_phenotype_experiment_reporting", bool2, iv8.G, false);
        V0 = a("measurement.experiment.enable_passthrough_experiment_reporting", bool2, tw8.H, false);
        W0 = a("measurement.set_default_event_parameters.fix_service_request_ordering", bool, pq8.b, false);
        X0 = a("measurement.set_default_event_parameters.fix_app_update_logging", bool2, mp8.b, false);
        Y0 = a("measurement.service.fix_stop_bundling_bug", bool2, u28.b, false);
        Z0 = a("measurement.gbraid_campaign.stop_lgclid", bool, jf8.H, false);
        a1 = a("measurement.gbraid_campaign.deep_link_url", bool, h88.J, false);
        b1 = a("measurement.gbraid_compaign.compaign_params_triggering_info_update", "gclid,gbraid,gad_campaignid", d38.c, false);
        c1 = a("measurement.edpb.service", bool, tw8.c, false);
        d1 = a("measurement.edpb.events_cached_in_no_data_mode", "_f,_v,_cmp", h88.c, false);
        e1 = a("measurement.robust_time_source_2", bool, fn8.H, false);
        f1 = a("measurement.manual_iap_logging.client_service", bool, bl8.J, false);
        g1 = a("measurement.dsid_consent_only.app_allowlist1", "", jf8.c, false);
        h1 = a("measurement.dsid_consent_only.app_allowlist2", "", bl8.c, false);
        i1 = a("measurement.dsid_consent_only.app_allowlist3", "", mp8.c, false);
        j1 = a("measurement.diagnostics.enabled", bool, iv8.c, false);
    }

    public static wme a(String str, Object obj, ace aceVar, boolean z2) {
        wme wmeVar = new wme(str, obj, aceVar);
        if (z2) {
            a.add(wmeVar);
        }
        return wmeVar;
    }
}
